#!/usr/bin/env python3
"""Real, small, reusable generator: one cnv-any tool name -> one new aac:AshConnector
individual appended to this pack's ontology.ttl.

Eliminates hand-editing ontology.ttl per new connector (ERRC: Eliminate). Takes exactly
one real input: a tool name from the real cnv-any manifest, e.g. "fabric__cache-stats"
(ERRC: Reduce). Derives resourceModule/domainModule/actionName/outputFile/tableName by
reading the naming convention already established by the 3 existing individuals
(AutofdePlannerCandidate/fabric__solve, AutofdePlannerCatalog/fabric__catalog,
AutofdePlannerMatch/fabric__match) -- it does not invent a new convention (ERRC: Raise --
the pack becomes self-extending instead of requiring a new hand-authored block per tool).

Naming convention observed in ontology.ttl (verified against the 3 existing individuals):
  - tool "fabric__<name>" (name may contain '-')
  - class local name:  Autofde Planner + PascalCase(name with '-'/'_' as word breaks)
      e.g. "cache-stats"  -> AutofdePlannerCacheStats
           "cache-hotset" -> AutofdePlannerCacheHotset
  - resourceModule:    "Xaas.Operations." + class local name
  - domainModule:      "Xaas.Operations"                         (constant, all 3 existing)
  - actionName:        "request_" + snake_case(name)             e.g. request_cache_stats
  - cnvDeployBaseUrlEnv: "cnv_deploy_base_url"                    (constant, all 3 existing)
  - outputFile:         "lib/xaas/operations/autofde_planner_" + snake_case(name) + ".ex"
  - tableName:          zero-required-argument tools (catalog-shaped, like fabric__catalog
                         and fabric__match) get the "_requests" suffix used by both existing
                         zero/optional-arg individuals:
                         "autofde_planner_" + snake_case(name) + "_requests"
                         (fabric__solve's "_candidates" tableName is solve-specific --
                         a real solve call, not a bare status/report tool -- and is not
                         reused here; both remaining tools, cache-stats/cache-hotset, are
                         confirmed zero-required-argument report tools, matching catalog).

This script is deliberately conservative: it REFUSES to run rather than guess if the tool
does not exist in the real manifest, if it already has an aac:AshConnector individual, or
if it carries required arguments this template does not yet know how to shape (only
fabric__solve and fabric__match, both already hand-added, use required/positional args
today).
"""
import json
import re
import sys
from pathlib import Path

PACK_DIR = Path(__file__).resolve().parent.parent
ONTOLOGY_PATH = PACK_DIR / "ontology.ttl"
MANIFEST_PATH = (
    Path.home()
    / "clap-noun-verb"
    / "clap-noun-verb-any"
    / "examples"
    / "autofde_lab_planners"
    / "cnv-any.json"
)


def snake(name: str) -> str:
    return name.replace("-", "_")


def pascal(name: str) -> str:
    return "".join(word.capitalize() for word in re.split(r"[-_]", name) if word)


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def find_command(manifest: dict, tool_name: str):
    """tool_name is the aac:invokeTool form, e.g. fabric__cache-stats."""
    if "__" not in tool_name:
        return None
    for cmd in manifest["commands"]:
        if "__".join(cmd["path"]) == tool_name:
            return cmd
    return None


def already_exists(ontology_text: str, invoke_tool: str) -> bool:
    return f'aac:invokeTool "{invoke_tool}"' in ontology_text


def build_individual(cmd: dict, tool_name: str) -> str:
    group, short_name = tool_name.split("__", 1)
    class_local = "AutofdePlanner" + pascal(short_name)
    resource_module = f"Xaas.Operations.{class_local}"
    domain_module = "Xaas.Operations"
    action_name = f"request_{snake(short_name)}"
    output_file = f"lib/xaas/operations/autofde_planner_{snake(short_name)}.ex"
    table_name = f"autofde_planner_{snake(short_name)}_requests"
    about = cmd.get("about", "")

    return f"""
aac:{class_local} a aac:AshConnector ;
  dcterms:description "Real connector: xaas Ash resource -> cnv-deploy POST /invoke tool {tool_name} ({about}, zero required arguments, confirmed clap-noun-verb-any/examples/autofde_lab_planners/cnv-any.json, generated by scripts/add_connector.py)" ;
  aac:resourceModule "{resource_module}" ;
  aac:domainModule "{domain_module}" ;
  aac:invokeTool "{tool_name}" ;
  aac:actionName "{action_name}" ;
  aac:cnvDeployBaseUrlEnv "cnv_deploy_base_url" ;
  aac:outputFile "{output_file}" ;
  aac:tableName "{table_name}" .
"""


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: add_connector.py <tool-name e.g. fabric__cache-stats>", file=sys.stderr)
        return 2

    tool_name = sys.argv[1]

    if not MANIFEST_PATH.exists():
        print(f"REFUSED: real manifest not found at {MANIFEST_PATH}", file=sys.stderr)
        return 1
    manifest = load_manifest()

    cmd = find_command(manifest, tool_name)
    if cmd is None:
        print(f"REFUSED: tool '{tool_name}' not found in real manifest {MANIFEST_PATH}", file=sys.stderr)
        return 1

    required_args = [a for a in cmd.get("arguments", []) if a.get("required")]
    if required_args:
        print(
            f"REFUSED: tool '{tool_name}' has {len(required_args)} required argument(s) "
            f"({[a['id'] for a in required_args]}) -- this generator only knows the "
            f"zero-required-argument connector shape (like fabric__catalog). Required-arg "
            f"tools (fabric__solve, fabric__match) were hand-shaped; extend the generator "
            f"deliberately before using it for another required-arg tool.",
            file=sys.stderr,
        )
        return 1

    ontology_text = ONTOLOGY_PATH.read_text()
    if already_exists(ontology_text, tool_name):
        print(f"REFUSED: aac:invokeTool \"{tool_name}\" already has an individual in {ONTOLOGY_PATH}", file=sys.stderr)
        return 1

    block = build_individual(cmd, tool_name)
    ONTOLOGY_PATH.write_text(ontology_text.rstrip("\n") + "\n" + block)
    print(f"OK: appended aac:AshConnector individual for '{tool_name}' to {ONTOLOGY_PATH}")
    print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
