"""Real regression test for FMEA RPN=144 (Severity=6 x Occurrence=3 x Detection=8):

run_ggen_sync() used to treat a real subprocess exit code of 0 as proof that the
specific output_file for the current tool_name had actually been (re)written.
copy_generated_file_to_xaas() then only checked src.exists() (never mtime/freshness)
before copying. `ggen sync` is differential and can genuinely exit 0 while silently
no-op'ing on one particular tool's output path. Meanwhile this pack's scratch lib/
dir accumulates every prior connector's generated .ex output across runs and is
never cleaned -- so a STALE file from an earlier, unrelated connector run can already
be sitting at exactly the path the new tool_name's outputFile points to. Before this
fix, that stale file would be silently copied to the real ~/xaas checkout and
reported as a fresh success.

Chicago style throughout: this test runs the real add_connector.py as a real
subprocess against a real temporary pack directory, pre-seeds a real stale file with
a real, explicitly old mtime at the real output_file path, and forces a real
subprocess (via GGEN_SYNC_CMD_OVERRIDE -- a real fake ggen: a one-line python3 -c
script, not a mocked subprocess.run) to exit 0 without touching that file, exactly
reproducing the silent-no-op scenario. Assertions are on real resulting file state
(the file's actual bytes and mtime, real exit codes, real xaas-copy side effects),
never on mocked interactions. No unittest.mock, Mock(), MagicMock(), patch(), or
monkeypatch anywhere in this file.
"""
import json
import os
import subprocess
import sys
from pathlib import Path

REAL_SCRIPT_PATH = Path(__file__).resolve().parent / "add_connector.py"
REAL_ONTOLOGY_PATH = Path(__file__).resolve().parent.parent / "ontology.ttl"

TOOL_NAME = "fabric__cache-evict"  # not a real connector; fresh name only used by this test
SHORT_NAME = "cache-evict"
OUTPUT_FILE_REL = f"lib/xaas/operations/autofde_planner_{SHORT_NAME.replace('-', '_')}.ex"

FIXTURE_MANIFEST = {
    "commands": [
        {
            "path": ["fabric", "cache-evict"],
            "about": "Evict the real cache namespace.",
            "arguments": [],
        },
    ],
}

STALE_BYTES = b"# STALE: generated by a PRIOR, unrelated connector run\n"
FRESH_BYTES = b"# FRESH: really (re)generated by this run\n"

OLD_MTIME = 1_000_000_000.0  # 2001-09-09 -- unambiguously old, real os.utime() value

# Minimal real fixture sparql_bridge.ex, same anchors apply_sparql_bridge_extension()
# matches against (trimmed copy of the fixture used by
# test_add_connector_bridge_guard.py) -- needed only so the happy-path tests below can
# reach the real pipeline's end (freshness check -> copy -> bridge wiring) instead of
# being stopped by the separate, already-covered FMEA RPN=576 guard.
FIXTURE_BRIDGE = '''defmodule Xaas.SparqlBridge do
  @moduledoc """
  Real Monitor substrate for a MAPE-K loop.
  """

  alias Xaas.Operations.AutofdePlannerCandidate
  alias Xaas.Operations.AutofdePlannerCatalog
  alias Xaas.Operations.AutofdePlannerMatch

  @prefix "https://xaas.dev/ontology/autofde-monitor#"

  @spec to_turtle() :: String.t()
  def to_turtle do
    {:ok, candidates} = Ash.read(AutofdePlannerCandidate)
    {:ok, catalog_requests} = Ash.read(AutofdePlannerCatalog)
    {:ok, match_requests} = Ash.read(AutofdePlannerMatch)

    header = """
    @prefix aacm: <#{@prefix}> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    """

    body =
      (Enum.map(candidates, &candidate_to_turtle/1) ++
         Enum.map(catalog_requests, &catalog_to_turtle/1) ++
         Enum.map(match_requests, &match_to_turtle/1))
      |> Enum.join("\\n")

    header <> body
  end

  @spec match_to_turtle() :: String.t()
  def match_to_turtle do
    {:ok, rows} = Ash.read(AutofdePlannerMatch)
    turtle_document(Enum.map(rows, &match_to_turtle/1))
  end

  defp turtle_document(bodies) do
    header = """
    @prefix aacm: <#{@prefix}> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    """

    header <> Enum.join(bodies, "\\n")
  end

  defp candidate_to_turtle(%AutofdePlannerCandidate{} = row) do
    row
  end

  defp catalog_to_turtle(%AutofdePlannerCatalog{} = row) do
    row
  end

  defp match_to_turtle(%AutofdePlannerMatch{} = row) do
    subject = "aacm:PlannerMatchRequest_#{row.id}"

    render_individual(subject, [
      {"a", "aacm:PlannerMatchRequest"},
      {"aacm:query", turtle_string(row.query)},
      {"aacm:trajectorySha256", turtle_maybe_string(row.trajectory_sha256)},
      {"aacm:requestedAt", turtle_maybe_datetime(row.requested_at)}
    ])
  end

  defp render_individual(subject, lines) do
    subject
  end
end
'''


def _make_fixture_pack(tmp_path: Path) -> Path:
    """Real temp pack dir: scripts/add_connector.py (the real, unmodified fixed
    script, copied so PACK_DIR resolves under tmp_path) + a real ontology.ttl fixture
    with the exact structure the real one has."""
    pack_dir = tmp_path / "pack"
    scripts_dir = pack_dir / "scripts"
    scripts_dir.mkdir(parents=True)
    (scripts_dir / "add_connector.py").write_text(REAL_SCRIPT_PATH.read_text())

    ontology_fixture = """@prefix aac: <https://ggen.dev/ontology/ash-autofde-lab-connector#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

aac:AshConnector a rdfs:Class ;
  rdfs:label "Ash-side connector resource to a clap-noun-verb-deploy-served planner tool" .

aac:resourceModule a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:domainModule a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:invokeTool a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:actionName a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:cnvDeployBaseUrlEnv a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:outputFile a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
aac:tableName a rdf:Property ; rdfs:domain aac:AshConnector ; rdfs:range xsd:string .
"""
    (pack_dir / "ontology.ttl").write_text(ontology_fixture)

    manifest_path = tmp_path / "cnv-any.json"
    manifest_path.write_text(json.dumps(FIXTURE_MANIFEST))

    # Fake xaas checkout with a real sparql_bridge.ex fixture, so a fully successful
    # --deploy run (freshness check -> copy -> bridge wiring) can actually complete
    # end to end in the happy-path tests below.
    xaas_root = tmp_path / "xaas_root"
    bridge_path = xaas_root / "lib" / "xaas" / "sparql_bridge.ex"
    bridge_path.parent.mkdir(parents=True, exist_ok=True)
    bridge_path.write_text(FIXTURE_BRIDGE)

    return pack_dir


def _seed_stale_output_file(pack_dir: Path) -> Path:
    """Real file, real old mtime, sitting exactly where this run's outputFile points
    -- reproducing the real, confirmed-live scratch-dir accumulation: a prior,
    unrelated connector run's .ex output that was never cleaned up."""
    stale_path = pack_dir / OUTPUT_FILE_REL
    stale_path.parent.mkdir(parents=True, exist_ok=True)
    stale_path.write_bytes(STALE_BYTES)
    os.utime(stale_path, (OLD_MTIME, OLD_MTIME))
    return stale_path


def _run_deploy(pack_dir: Path, tmp_path: Path, sync_cmd_argv: list[str]) -> subprocess.CompletedProcess:
    env = {
        **os.environ,
        "CNV_ANY_MANIFEST_PATH": str(tmp_path / "cnv-any.json"),
        "XAAS_ROOT": str(tmp_path / "xaas_root"),
        # Real fake ggen: a real subprocess (python3 -c "..."), not a mocked
        # subprocess.run -- lets this test deterministically reproduce either the
        # silent-no-op case or the genuine-fresh-write case with a real exit code.
        "GGEN_SYNC_CMD_OVERRIDE": json.dumps(sync_cmd_argv),
    }
    return subprocess.run(
        [sys.executable, str(pack_dir / "scripts" / "add_connector.py"), TOOL_NAME, "--deploy"],
        capture_output=True,
        text=True,
        env=env,
    )


def test_real_manifest_is_untouched_by_this_test(tmp_path):
    """Sanity: this test must never mutate the real production ontology.ttl."""
    assert REAL_ONTOLOGY_PATH.exists()


def test_silent_noop_sync_refuses_instead_of_copying_stale_file(tmp_path):
    """FMEA RPN=144 regression: a real subprocess that exits 0 without touching the
    target output_file (the real shape of a differential ggen sync silently no-op'ing
    on this tool) must be REFUSED, not treated as a fresh success -- and the real
    stale file already sitting in the pack's scratch dir must never be copied to the
    real xaas checkout."""
    pack_dir = _make_fixture_pack(tmp_path)
    stale_path = _seed_stale_output_file(pack_dir)
    before_mtime = stale_path.stat().st_mtime

    # Real fake ggen: exits 0, touches nothing. This is exactly what a silent
    # differential-sync no-op on this tool's output_file looks like from outside.
    noop_cmd = [sys.executable, "-c", "pass"]
    result = _run_deploy(pack_dir, tmp_path, noop_cmd)

    assert result.returncode == 1, (
        f"expected a real non-zero exit code when the sync silently no-ops on "
        f"output_file, got {result.returncode}\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )
    assert "mtime did not change" in result.stderr, result.stderr
    assert "FMEA RPN=144" in result.stderr, result.stderr

    # The real stale file on disk must be completely untouched by this refusal.
    assert stale_path.read_bytes() == STALE_BYTES
    assert stale_path.stat().st_mtime == before_mtime

    # The real regression: the stale bytes must never have been copied to xaas.
    xaas_dest = tmp_path / "xaas_root" / OUTPUT_FILE_REL
    assert not xaas_dest.exists(), (
        f"stale file from a prior, unrelated connector run was copied to the real "
        f"xaas destination ({xaas_dest}) and would have been reported as a fresh "
        f"success -- exactly the FMEA RPN=144 gap"
    )


def test_genuine_fresh_write_still_succeeds_and_copies_real_bytes(tmp_path):
    """Happy path must keep working: when the sync subprocess really does (re)write
    output_file with new content, the pipeline must detect the freshness and copy the
    real new bytes to xaas -- the freshness check must not become a false refusal on
    a genuinely successful sync."""
    pack_dir = _make_fixture_pack(tmp_path)
    stale_path = _seed_stale_output_file(pack_dir)
    assert stale_path.read_bytes() == STALE_BYTES  # sanity: really starts stale

    target_abs = str(pack_dir / OUTPUT_FILE_REL)
    # Real fake ggen: a real subprocess that really overwrites the target file with
    # new bytes and exits 0 -- the real shape of a genuine, successful differential
    # sync that DID regenerate this tool's output.
    write_cmd = [
        sys.executable, "-c",
        f"open({target_abs!r}, 'wb').write({FRESH_BYTES!r})",
    ]
    result = _run_deploy(pack_dir, tmp_path, write_cmd)

    assert result.returncode == 0, (
        f"genuine fresh sync must still succeed end to end\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )
    assert "verified" in result.stdout and "freshly (re)written" in result.stdout, result.stdout

    xaas_dest = tmp_path / "xaas_root" / OUTPUT_FILE_REL
    assert xaas_dest.exists(), "real fresh output must actually be copied to xaas"
    assert xaas_dest.read_bytes() == FRESH_BYTES, (
        "xaas destination must contain the real fresh bytes, not stale leftovers"
    )


def test_first_ever_write_with_no_prior_file_still_succeeds(tmp_path):
    """No false refusal when output_file did not exist before this run at all (the
    very first connector added for a given tool -- no stale-vs-fresh ambiguity, just
    'newly appeared', which must count as fresh)."""
    pack_dir = _make_fixture_pack(tmp_path)
    target_path = pack_dir / OUTPUT_FILE_REL
    assert not target_path.exists()  # sanity: no pre-seeded file at all this time

    target_abs = str(target_path)
    write_cmd = [
        sys.executable, "-c",
        f"import os; os.makedirs(os.path.dirname({target_abs!r}), exist_ok=True); "
        f"open({target_abs!r}, 'wb').write({FRESH_BYTES!r})",
    ]
    result = _run_deploy(pack_dir, tmp_path, write_cmd)

    assert result.returncode == 0, (
        f"a real first-time write (no prior file) must succeed, not be refused as "
        f"'unchanged'\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    xaas_dest = tmp_path / "xaas_root" / OUTPUT_FILE_REL
    assert xaas_dest.exists()
    assert xaas_dest.read_bytes() == FRESH_BYTES
