"""Scorecard observer against real temporary git repositories (real ``git archive``).

Chicago style: repositories, pins and predecessor closures are real files and real commits in a
temporary directory; the observer streams real archives; assertions are on the observation.
"""

from __future__ import annotations

import contextlib
import io
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from scripts import observe_scorecard as obs

REL, PRE = "v9.9.2", "v9.9.1"
BLOCK = "".join(f"value_{i} = compute({i})\n" for i in range(8))


def git(repo: Path, *args: str) -> str:
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "t",
        "GIT_AUTHOR_EMAIL": "t@example.invalid",
        "GIT_COMMITTER_NAME": "t",
        "GIT_COMMITTER_EMAIL": "t@example.invalid",
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_NOSYSTEM": "1",
    }
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, check=True, env=env).stdout.decode().strip()


def commit(repo: Path, files: dict[str, str]) -> str:
    if not (repo / ".git").exists():
        repo.mkdir(parents=True, exist_ok=True)
        git(repo, "init", "-q", "-b", "main")
    for rel, text in files.items():
        (repo / rel).parent.mkdir(parents=True, exist_ok=True)
        (repo / rel).write_text(text)
    git(repo, "add", "--", *files)
    git(repo, "commit", "-q", "-m", "c")
    return git(repo, "rev-parse", "HEAD")


class ObserveScorecardTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        base = Path(self.tmp.name)
        self.repos = base / "repos"
        self.root = base / "root"
        mk = self.repos / "ggen-marketplace"
        self.mk = commit(mk, {"packs/p/tpl.py": "a = 1\nb = 2\nc = 3\nd = 4\ne = 5\n"})
        app = self.repos / "app"
        self.app_old = commit(app, {"src/old.py": "print('old')\n", "HANDWRITTEN.md": "src/hand.py | e | gap | owner | d\n"})
        self.app_side = git(app, "rev-parse", "HEAD")
        self.app_new = commit(
            app,
            {
                "src/hand.py": "x = 1\ny = 2\n",
                "src/gen.py": "# Generated by ggen\nq = 1\n",
                "vendor/tpl.py": "a = 1\nb = 2\nc = 3\nd = 4\ne = 5\n",
                "src/one.py": BLOCK,
                "src/two.py": "header()\n" + BLOCK,
            },
        )
        self._write_release(REL, {"ggen-marketplace": self.mk, "app": self.app_new})
        self._write_closure(PRE, [("seanchatmangpt/app", self.app_old), ("seanchatmangpt/ggen-marketplace", self.mk)])

    def tearDown(self):
        self.tmp.cleanup()

    def _write_release(self, release: str, shas: dict[str, str]) -> None:
        d = self.root / "release" / release
        d.mkdir(parents=True, exist_ok=True)
        pins = {
            "root_repository": "seanchatmangpt/app",
            "repos": {name: {"repository": f"seanchatmangpt/{name}", "sha": sha} for name, sha in shas.items()},
        }
        (d / "pins.json").write_text(json.dumps(pins))

    def _write_closure(self, release: str, rows: list[tuple[str, str]]) -> None:
        d = self.root / "release" / release
        d.mkdir(parents=True, exist_ok=True)
        (d / "closure.json").write_text(json.dumps({"subjects": [{"repository": r, "sha": s} for r, s in rows]}))

    def observe(self):
        return obs.observe(self.root, REL, PRE, self.repos)

    def test_measures_the_pinned_archives(self):
        doc = self.observe()
        app = doc["releases"][REL]["repos"]["seanchatmangpt/app"]
        self.assertEqual(app["sha"], self.app_new)
        self.assertEqual((app["generated_files"], app["generated_loc"]), (1, 2))
        self.assertEqual((app["handwritten"]["matched_files"], app["handwritten"]["loc"]), (1, 2))
        self.assertEqual((app["marketplace_reused_files"], app["marketplace_reused_loc"]), (1, 5))
        self.assertIsNone(doc["releases"][REL]["repos"]["seanchatmangpt/ggen-marketplace"]["marketplace_reused_loc"])
        old = doc["releases"][PRE]["repos"]["seanchatmangpt/app"]
        self.assertEqual((old["sha"], old["handwritten"]["unmatched_entries"]), (self.app_old, ["HANDWRITTEN.md:src/hand.py"]))

    def test_duplication_is_measured_on_new_surfaces_only(self):
        surfaces = self.observe()["new_surfaces"]
        self.assertEqual(surfaces["repos"]["seanchatmangpt/app"]["files"], 4)  # hand, one, two, vendor (gen.py is generated)
        self.assertEqual(surfaces["duplicated_loc"], 2 * 8)
        self.assertEqual(surfaces["no_predecessor"], [])

    def test_observation_is_byte_deterministic_and_check_detects_drift(self):
        first = obs.dump(self.observe())
        self.assertEqual(first, obs.dump(self.observe()))
        target = self.root / "release" / REL / obs.OUT
        argv = ["--release", REL, "--predecessor", PRE, "--root", str(self.root), "--repos-root", str(self.repos)]
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(obs.main(argv + ["--write"]), 0)
            self.assertEqual(obs.main(argv + ["--check"]), 0)
        self.assertEqual(target.read_bytes(), first)
        newer = commit(self.repos / "app", {"src/three.py": "z = 3\n"})
        self._write_release(REL, {"ggen-marketplace": self.mk, "app": newer})
        with contextlib.redirect_stdout(io.StringIO()) as out:
            self.assertEqual(obs.main(argv + ["--check"]), 2)
        self.assertIn("REFUSED:OBSERVATION_DRIFT", out.getvalue())
        self.assertNotIn(str(self.root), first.decode())

    def test_predecessor_is_descendant_most_and_divergence_is_typed(self):
        self._write_closure(PRE, [("seanchatmangpt/app", self.app_old), ("seanchatmangpt/app", self.app_new)])
        self.assertEqual(obs.predecessor_subjects(self.root, PRE, self.repos)["seanchatmangpt/app"]["sha"], self.app_new)
        app = self.repos / "app"
        git(app, "checkout", "-q", "-b", "side", self.app_old)
        side = commit(app, {"src/side.py": "s = 1\n"})
        self._write_closure(PRE, [("seanchatmangpt/app", side), ("seanchatmangpt/app", self.app_new)])
        got = obs.predecessor_subjects(self.root, PRE, self.repos)["seanchatmangpt/app"]
        self.assertIsNone(got["sha"])
        self.assertTrue(got["error"].startswith("PREDECESSOR_AMBIGUOUS"))
        doc = self.observe()
        self.assertIn("seanchatmangpt/app", doc["new_surfaces"]["no_predecessor"])

    def test_unarchivable_pin_is_a_typed_error_not_a_zero(self):
        self._write_release(REL, {"ggen-marketplace": self.mk, "app": "0" * 40})
        app = self.observe()["releases"][REL]["repos"]["seanchatmangpt/app"]
        self.assertTrue(app["error"].startswith("ARCHIVE_FAILED:app@" + "0" * 40))
        self.assertNotIn("loc", app)


if __name__ == "__main__":
    unittest.main()
