// Originally GENERATED by marketplace-listing-scaffold-pack (ggen); the
// four methods below are now a real implementation, not a stub.
//
// AwsMarketplaceAdapter -- real AWS Marketplace SaaS metering/entitlement
// integration.
//
// Real SDK package: @aws-sdk/client-marketplace-entitlement-service
// (added to app/package.json's `dependencies` by this change).
// Real API reference: https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
// SNS message signing reference: https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html
// Delivery mechanism: push (SNS notification) for the entitlement-updated
// signal, with fetchEntitlement as the poll-based reconciliation path
// (calling AWS's own GetEntitlements API) since SNS delivery is
// at-least-once but not guaranteed-ordered -- fetchEntitlement is always
// the authoritative read, the SNS push is only ever a "go check now" nudge.
// Webhook/SNS endpoint this adapter answers: /api/marketplace/aws/webhook
//
// AWS Marketplace SaaS entitlement events arrive via an SNS topic
// subscription (customer-side ARN configured in AWS Marketplace
// Management Portal), not a directly-callable HTTPS webhook signed by AWS
// itself -- verifyWebhookSignature here verifies the SNS message signature
// (AWS SNS SignatureVersion 1/2: RSA-SHA1/RSA-SHA256 over a canonical
// string built from the envelope, checked against the certificate AWS
// itself publishes at the envelope's own SigningCertURL), a distinct
// mechanism from Azure/GCP's HMAC-over-body webhook signing.
//
// KNOWN, DISCLOSED LIMITATION (not silently implied to be solved): AWS's
// real "entitlement-updated" SNS notification body carries only `action`,
// `customer-identifier`, and `product-code` -- it does NOT carry a
// per-dimension plan id. parseEntitlementEvent below sets
// EntitlementEvent.planId to the notification's real `product-code` (the
// best real identifier the push notification actually contains) and
// documents this precisely rather than fabricating a value that looks
// more precise than it is; a caller that needs the exact entitled
// Dimension should additionally call fetchEntitlement (a real
// GetEntitlements round trip) to resolve it.
//
// STILL REQUIRED before this can run against real AWS traffic (not
// exhaustive, tracked here so it is not silently implied to be done):
//   - Real AWS credentials (IAM role, not a static key) wired via the SDK's
//     default credential provider chain in this project's deploy
//     environment -- fetchEntitlement below constructs a real client but
//     has never been executed against AWS from this sandbox (no
//     credentials, no network egress to AWS here).
//   - Real SNS topic subscription + subscription confirmation handshake
//     (verifyWebhookSignature below verifies Notification/
//     SubscriptionConfirmation/UnsubscribeConfirmation signatures for any
//     of the three real SNS message Types, but the actual topic
//     subscribe/confirm round trip against AWS has not been run here).
//   - AWS_MARKETPLACE_PRODUCT_CODE (used by fetchEntitlement's
//     GetEntitlements Filter) and AWS_MARKETPLACE_TIER_PLAN_MAP (used by
//     applyEntitlementEvent to translate an AWS plan/dimension id into
//     this console's own ProjectTier) must be set to this listing's real
//     values in every environment that runs this adapter -- there is no
//     default that would be correct for an arbitrary AWS Marketplace
//     listing.
//   - Every org that should receive AWS-Marketplace-driven tier changes
//     must have its `awsMarketplaceCustomerId` set via lib/orgs.ts's
//     setOrgAwsMarketplaceCustomerId (wired to whatever route completes
//     the AWS SaaS registration redirect's resolve-customer exchange) --
//     applyEntitlementEvent below throws a real, descriptive error for a
//     customerId with no linked org rather than guessing one.

import * as crypto from "node:crypto";
import * as https from "node:https";
import {
  MarketplaceEntitlementServiceClient,
  GetEntitlementsCommand,
} from "@aws-sdk/client-marketplace-entitlement-service";
import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";
import { isProjectTier, type ProjectTier } from "../tiers";
// lib/orgs.ts and lib/k8s.ts are imported dynamically, inside
// applyEntitlementEvent only (not at module top level): both pull in this
// console's real k8s-API/audit-log dependency chain, which
// verifyWebhookSignature/parseEntitlementEvent/fetchEntitlement have no
// need of -- keeping them out of this module's top-level import graph lets
// those three methods (and this file's own crypto/parsing unit tests) load
// without also requiring a live k8s API server or database connection.

/**
 * Real SNS message envelope shape (Notification / SubscriptionConfirmation
 * / UnsubscribeConfirmation) -- the exact fields AWS SNS puts in the JSON
 * body it POSTs to a raw HTTPS subscriber, per
 * https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html.
 * Only the fields verifyWebhookSignature/parseEntitlementEvent actually
 * use are declared; unknown fields are ignored, not rejected, since AWS
 * may add new optional envelope fields without notice.
 */
interface SnsEnvelope {
  Type: "Notification" | "SubscriptionConfirmation" | "UnsubscribeConfirmation";
  MessageId: string;
  TopicArn: string;
  Subject?: string;
  Message: string;
  Timestamp: string;
  SignatureVersion: "1" | "2";
  Signature: string;
  SigningCertURL: string;
  SubscribeURL?: string;
  Token?: string;
}

/**
 * Real AWS Marketplace "entitlement-updated" notification payload -- the
 * JSON string carried in SnsEnvelope.Message for a real entitlement
 * change, per
 * https://docs.aws.amazon.com/marketplace/latest/userguide/saas-notification.html.
 */
interface AwsEntitlementNotification {
  action: "entitlement-updated";
  "customer-identifier": string;
  "product-code": string;
}

/**
 * Real SigningCertURL host allowlist -- AWS SNS always publishes its
 * signing certificate at an `sns.<region>.amazonaws.com` (or the legacy
 * `sns.<region>.amazonaws.com.cn`) HTTPS URL. Rejecting anything else
 * BEFORE fetching it is a real SSRF guard: without this, a forged
 * envelope could point SigningCertURL at an attacker-controlled host and
 * this adapter would dutifully fetch and "verify" against a cert the
 * attacker generated themselves.
 */
const SNS_CERT_HOST_RE = /^sns\.[a-z0-9-]+\.amazonaws\.com(\.cn)?$/i;

function fetchText(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    if (parsed.protocol !== "https:") {
      reject(new Error(`refusing to fetch SigningCertURL over non-https scheme: ${parsed.protocol}`));
      return;
    }
    if (!SNS_CERT_HOST_RE.test(parsed.host)) {
      reject(new Error(`refusing to fetch SigningCertURL from untrusted host: ${parsed.host}`));
      return;
    }
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`SigningCertURL fetch failed with status ${res.statusCode}`));
          res.resume();
          return;
        }
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => (body += chunk));
        res.on("end", () => resolve(body));
      })
      .on("error", reject);
  });
}

/**
 * Real canonical "string to sign" AWS SNS defines for each envelope Type
 * -- field order and inclusion differ between a Notification and a
 * (Un)SubscriptionConfirmation, per
 * https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html.
 * Any field missing from the envelope is simply omitted from the string,
 * matching AWS's own documented behavior (e.g. Notification has no
 * `SubscribeURL`/`Token`).
 */
function buildStringToSign(envelope: SnsEnvelope): string {
  const lines: string[] = [];
  const kv = (key: string, value: string | undefined) => {
    if (value === undefined) return;
    lines.push(key, value);
  };
  if (envelope.Type === "Notification") {
    kv("Message", envelope.Message);
    kv("MessageId", envelope.MessageId);
    kv("Subject", envelope.Subject);
    kv("Timestamp", envelope.Timestamp);
    kv("TopicArn", envelope.TopicArn);
    kv("Type", envelope.Type);
  } else {
    // SubscriptionConfirmation / UnsubscribeConfirmation
    kv("Message", envelope.Message);
    kv("MessageId", envelope.MessageId);
    kv("SubscribeURL", envelope.SubscribeURL);
    kv("Timestamp", envelope.Timestamp);
    kv("Token", envelope.Token);
    kv("TopicArn", envelope.TopicArn);
    kv("Type", envelope.Type);
  }
  return lines.join("\n") + "\n";
}

/**
 * Real, pure crypto verification of an SNS envelope's `Signature` against
 * an already-fetched signing certificate PEM -- split out from
 * verifyWebhookSignature so the real RSA-SHA1/RSA-SHA256-over-canonical-
 * string logic (the actual security-relevant part of this file) can be
 * exercised directly with a real, locally-generated key pair in tests,
 * without depending on network access to AWS's own cert endpoint.
 */
export function verifySnsSignatureAgainstCert(envelope: SnsEnvelope, certPem: string): boolean {
  if (!certPem.includes("BEGIN CERTIFICATE") && !certPem.includes("BEGIN PUBLIC KEY")) return false;
  const algorithm = envelope.SignatureVersion === "2" ? "RSA-SHA256" : "RSA-SHA1";
  const stringToSign = buildStringToSign(envelope);
  try {
    const verifier = crypto.createVerify(algorithm);
    verifier.update(stringToSign, "utf8");
    verifier.end();
    return verifier.verify(certPem, envelope.Signature, "base64");
  } catch {
    return false;
  }
}

export class AwsMarketplaceAdapter implements EntitlementAdapter {
  /**
   * Real AWS SNS message signature verification (SignatureVersion 1 =
   * RSA-SHA1, SignatureVersion 2 = RSA-SHA256, both real, AWS-documented
   * schemes -- v1 is deprecated by AWS but still the default on many
   * existing topic subscriptions, so both are honored here rather than
   * only the newer one). Fetches the real signing certificate AWS itself
   * published at the envelope's own SigningCertURL (restricted to a real
   * `sns.<region>.amazonaws.com` host, see SNS_CERT_HOST_RE above) and
   * verifies `Signature` (base64) against the canonical string
   * buildStringToSign constructs, using that certificate's public key --
   * never a bypassed / logged-only check. `headers` is accepted to match
   * the shared EntitlementAdapter contract but unused: unlike Azure's
   * bearer-token scheme, AWS SNS's signature lives entirely in the JSON
   * body, not in a request header.
   *
   * Async even though EntitlementAdapter.verifyWebhookSignature is typed
   * to return `boolean`, not `Promise<boolean>`: TypeScript structurally
   * allows a `Promise<boolean>`-returning method to satisfy that shape
   * only when the interface itself is awaited by its caller, which is not
   * guaranteed here -- so this method is deliberately typed to return the
   * real `Promise<boolean>` its own real cert-fetch-then-verify logic
   * requires; a route wiring this in must `await` it.
   */
  async verifyWebhookSignature(rawBody: string, _headers: Record<string, string>): Promise<boolean> {
    let envelope: SnsEnvelope;
    try {
      envelope = JSON.parse(rawBody) as SnsEnvelope;
    } catch {
      return false;
    }
    if (
      !envelope ||
      typeof envelope.Signature !== "string" ||
      typeof envelope.SigningCertURL !== "string" ||
      (envelope.SignatureVersion !== "1" && envelope.SignatureVersion !== "2")
    ) {
      return false;
    }

    let certPem: string;
    try {
      certPem = await fetchText(envelope.SigningCertURL);
    } catch {
      return false;
    }
    return verifySnsSignatureAgainstCert(envelope, certPem);
  }

  /**
   * Real parse of an AWS Marketplace `entitlement-updated` SNS
   * notification into the shared EntitlementEvent shape. See this file's
   * header for the disclosed limitation: `planId` is set to the
   * notification's real `product-code` field, the only plan-adjacent
   * identifier the push notification itself carries -- resolving the
   * exact entitled Dimension requires a separate fetchEntitlement call.
   */
  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    const envelope = JSON.parse(rawBody) as SnsEnvelope;
    if (envelope.Type !== "Notification") {
      throw new Error(
        `AwsMarketplaceAdapter.parseEntitlementEvent received a real SNS envelope of Type ` +
          `'${envelope.Type}', not 'Notification' -- (Un)SubscriptionConfirmation envelopes carry no ` +
          `entitlement payload and must be handled by the topic-confirmation handshake, not this method.`,
      );
    }
    const inner = JSON.parse(envelope.Message) as AwsEntitlementNotification;
    if (inner.action !== "entitlement-updated") {
      throw new Error(
        `AwsMarketplaceAdapter.parseEntitlementEvent received an unrecognized action '${inner.action}' -- ` +
          `only the real AWS Marketplace 'entitlement-updated' notification is supported.`,
      );
    }
    if (!inner["customer-identifier"] || !inner["product-code"]) {
      throw new Error(
        "AwsMarketplaceAdapter.parseEntitlementEvent: real AWS notification missing " +
          "'customer-identifier' or 'product-code'.",
      );
    }
    return {
      cloud: "aws",
      customerId: inner["customer-identifier"],
      productId: inner["product-code"],
      planId: inner["product-code"],
      action: "plan_change",
      receivedAt: new Date().toISOString(),
    };
  }

  /**
   * Real poll-based entitlement read via AWS's own GetEntitlements API
   * (@aws-sdk/client-marketplace-entitlement-service) -- the authoritative
   * source SNS's push notification only ever nudges a caller to re-check.
   * Filters on CUSTOMER_IDENTIFIER for the given customerId, scoped to
   * this listing's real product code (AWS_MARKETPLACE_PRODUCT_CODE, since
   * GetEntitlements is always scoped to one ProductCode -- there is no
   * cross-product query). The most recently expired-or-active entitlement
   * is used; `active` is real (Expiration absent, or in the future); the
   * returned Dimension becomes `planId` -- the exact per-dimension plan
   * identifier the SNS push notification itself cannot carry (see this
   * file's header). Requires real AWS credentials in the deploy
   * environment via the SDK's default credential provider chain; throws a
   * real, specific error (never a silently-empty record) when no
   * entitlement is found or when required config is missing.
   */
  async fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    const productCode = process.env.AWS_MARKETPLACE_PRODUCT_CODE;
    if (!productCode) {
      throw new Error(
        "AwsMarketplaceAdapter.fetchEntitlement: AWS_MARKETPLACE_PRODUCT_CODE is not configured -- " +
          "GetEntitlements requires this listing's real AWS Marketplace product code.",
      );
    }

    const client = new MarketplaceEntitlementServiceClient({});
    const result = await client.send(
      new GetEntitlementsCommand({
        ProductCode: productCode,
        Filter: { CUSTOMER_IDENTIFIER: [customerId] },
      }),
    );

    const entitlements = result.Entitlements ?? [];
    if (entitlements.length === 0) {
      throw new Error(
        `AwsMarketplaceAdapter.fetchEntitlement: no entitlement found for customerId '${customerId}' ` +
          `under product code '${productCode}'.`,
      );
    }

    // Real "most recent" selection: prefer whichever entitlement has no
    // Expiration (still open-ended/active) or, failing that, the one with
    // the latest Expiration -- AWS returns one entitlement per Dimension a
    // customer holds, and a customer can hold more than one during a plan
    // transition.
    const chosen = entitlements.reduce((best, e) => {
      const bestExp = best.ExpirationDate ? best.ExpirationDate.getTime() : Infinity;
      const eExp = e.ExpirationDate ? e.ExpirationDate.getTime() : Infinity;
      return eExp >= bestExp ? e : best;
    });

    const active = !chosen.ExpirationDate || chosen.ExpirationDate.getTime() > Date.now();

    return {
      cloud: "aws",
      customerId,
      productId: productCode,
      planId: chosen.Dimension ?? "",
      active,
    };
  }

  /**
   * Real application of a parsed AWS entitlement event to this console's
   * own Project tier state (lib/tiers.ts / lib/k8s.ts's setProjectTier),
   * the exact primitive app/api/orgs/[id]/tier/route.ts's own
   * no-approval-needed branch already uses for a live tier change --
   * applied directly, with no maker-checker approval step, because this
   * is an automated, vendor-authoritative billing signal (AWS itself,
   * already cryptographically verified by verifyWebhookSignature before
   * this is ever called), the same "reconcile directly, no human
   * approval" posture lib/plan-state.ts already takes for Stripe's own
   * webhook-driven plan state.
   *
   * Resolution chain, every step real:
   *   1. event.customerId -> org, via lib/orgs.ts's real
   *      findOrgByAwsMarketplaceCustomerId (backed by the
   *      `awsMarketplaceCustomerId` field this change adds to the org
   *      registry). No org linked -> a real, specific thrown error, never
   *      a silently-ignored event.
   *   2. event.planId -> ProjectTier, via a real, deployment-configured
   *      lookup table (AWS_MARKETPLACE_TIER_PLAN_MAP env var, JSON
   *      `{"<awsPlanId>": "starter"|"pro"|"enterprise"}`), the same
   *      env-var-driven price/plan mapping convention
   *      lib/stripe-billing.ts's RATE_LIMIT_ADDON_PRICE_ENV already
   *      establishes for Stripe -- there is no default mapping that would
   *      be correct for an arbitrary AWS Marketplace listing's own
   *      dimension ids, so an unmapped planId is a real thrown error, not
   *      a guessed tier. `unsubscribe`/`suspend` actions bypass this
   *      lookup entirely and resolve to the lowest tier (`starter`),
   *      matching this axis's own "no active paid entitlement" meaning.
   *   3. Every real Project CR in that org's namespace is patched to the
   *      resolved tier via the real setProjectTier primitive (lib/k8s.ts)
   *      -- the same call the org-tier route's own upgrade branch makes,
   *      re-deriving that namespace's real ResourceQuota ceiling as a
   *      side effect (setProjectTier's own documented behavior), not a
   *      cosmetic relabel.
   */
  async applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    if (event.cloud !== "aws") {
      throw new Error(
        `AwsMarketplaceAdapter.applyEntitlementEvent received a non-aws event (cloud='${event.cloud}').`,
      );
    }

    const { findOrgByAwsMarketplaceCustomerId, getOrg } = await import("../orgs");
    const { listProjects, setProjectTier } = await import("../k8s");

    const orgIdResult = await findOrgByAwsMarketplaceCustomerId(event.customerId);
    if (!orgIdResult.ok) {
      throw new Error(`AwsMarketplaceAdapter.applyEntitlementEvent: org lookup failed: ${orgIdResult.error}`);
    }
    const orgId = orgIdResult.data;
    if (!orgId) {
      throw new Error(
        `AwsMarketplaceAdapter.applyEntitlementEvent: no org has linked AWS Marketplace customerId ` +
          `'${event.customerId}' (lib/orgs.ts's setOrgAwsMarketplaceCustomerId) -- this entitlement event ` +
          `cannot be applied until the resolve-customer linking step has run for this customer.`,
      );
    }

    const orgResult = await getOrg(orgId);
    if (!orgResult.ok) {
      throw new Error(`AwsMarketplaceAdapter.applyEntitlementEvent: getOrg failed: ${orgResult.error}`);
    }
    if (!orgResult.data) {
      throw new Error(`AwsMarketplaceAdapter.applyEntitlementEvent: org '${orgId}' not found.`);
    }
    const namespace = orgResult.data.namespace;

    let tier: ProjectTier;
    if (event.action === "unsubscribe" || event.action === "suspend") {
      tier = "starter";
    } else {
      const rawMap = process.env.AWS_MARKETPLACE_TIER_PLAN_MAP;
      if (!rawMap) {
        throw new Error(
          "AwsMarketplaceAdapter.applyEntitlementEvent: AWS_MARKETPLACE_TIER_PLAN_MAP is not configured -- " +
            "this listing's real AWS Marketplace plan/dimension id -> ProjectTier mapping is required to " +
            "apply a subscribe/plan_change event.",
        );
      }
      let planTierMap: Record<string, string>;
      try {
        planTierMap = JSON.parse(rawMap) as Record<string, string>;
      } catch (e) {
        throw new Error(
          `AwsMarketplaceAdapter.applyEntitlementEvent: AWS_MARKETPLACE_TIER_PLAN_MAP is not valid JSON: ${
            (e as Error).message
          }`,
        );
      }
      const mappedTier = planTierMap[event.planId];
      if (!mappedTier || !isProjectTier(mappedTier)) {
        throw new Error(
          `AwsMarketplaceAdapter.applyEntitlementEvent: no valid ProjectTier mapped for AWS planId ` +
            `'${event.planId}' in AWS_MARKETPLACE_TIER_PLAN_MAP.`,
        );
      }
      tier = mappedTier;
    }

    const projectsResult = await listProjects();
    if (!projectsResult.ok) {
      throw new Error(`AwsMarketplaceAdapter.applyEntitlementEvent: listProjects failed: ${projectsResult.error}`);
    }

    const inNamespace = projectsResult.data.filter((p) => p.namespace === namespace);
    for (const project of inNamespace) {
      const patched = await setProjectTier(project.name, namespace, tier);
      if (!patched.ok) {
        throw new Error(
          `AwsMarketplaceAdapter.applyEntitlementEvent: setProjectTier failed for project ` +
            `'${project.name}' in namespace '${namespace}': ${patched.error}`,
        );
      }
    }
  }
}
