// GENERATED by marketplace-listing-scaffold-pack (ggen). Do not hand-edit.
//
// AwsMarketplaceAdapter -- STUB. Every method below throws or returns a
// placeholder; none call the real AWS SDK yet.
//
// Real SDK package (not yet a dependency of this project): @aws-sdk/client-marketplace-metering
// Real API reference: https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
// Delivery mechanism: push (SNS notification) with a fetchEntitlement poll fallback via @aws-sdk/client-marketplace-entitlement-service, since AWS Marketplace SNS delivery is at-least-once but not guaranteed-ordered
// Webhook/SNS endpoint this adapter answers: /api/marketplace/aws/webhook
//
// AWS Marketplace SaaS entitlement events arrive via an SNS topic subscription (customer-side ARN configured in AWS Marketplace Management Portal), not a directly-callable HTTPS webhook signed by AWS itself -- verifyWebhookSignature here means verifying the SNS message signature (AWS SNS SignatureVersion 1/2), a distinct mechanism from Azure/GCP's HMAC-over-body webhook signing.
//
// STILL REQUIRED before this is real (not exhaustive, tracked here so it's
// not silently implied to be done):
//   - Real AWS credentials (IAM role, not a static key) wired via
//     @aws-sdk/credential-providers in this project's deploy environment.
//   - Real SNS topic subscription + subscription confirmation handshake.
//   - A real round trip against the AWS Marketplace SaaS sandbox
//     (resolve-customer, register-usage) has not been run.

import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";

export class AwsMarketplaceAdapter implements EntitlementAdapter {
  verifyWebhookSignature(rawBody: string, headers: Record<string, string>): boolean {
    // TODO(marketplace-listing-scaffold-pack): implement against @aws-sdk/client-marketplace-metering.
    // See https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
    throw new Error("AwsMarketplaceAdapter.verifyWebhookSignature is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    // TODO(marketplace-listing-scaffold-pack): implement against @aws-sdk/client-marketplace-metering.
    // See https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
    throw new Error("AwsMarketplaceAdapter.parseEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    // TODO(marketplace-listing-scaffold-pack): implement against @aws-sdk/client-marketplace-metering.
    // See https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
    throw new Error("AwsMarketplaceAdapter.fetchEntitlement is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    // TODO(marketplace-listing-scaffold-pack): implement against @aws-sdk/client-marketplace-metering.
    // See https://docs.aws.amazon.com/marketplace/latest/userguide/saas-metered-billing-events.html
    throw new Error("AwsMarketplaceAdapter.applyEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

}
