// Was GENERATED by marketplace-listing-scaffold-pack (ggen) as a throw-stub;
// hand-implemented below against the real Microsoft SaaS Fulfillment API and
// this codebase's already-real, already-wired Azure marketplace logic in
// lib/marketplace-runtime.ts (used by app/api/marketplace/[provider]/{webhook,usage,register}
// routes). This file's EntitlementAdapter interface is a coarser, cross-cloud
// shape (no subscription id, no event id, no quantity) than
// MarketplaceEntitlementEvent -- see the per-method notes below for exactly how
// each field is derived from what EntitlementEvent actually carries.
//
// Real API reference: https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
//
// verifyWebhookSignature validates the AAD (Entra ID) bearer token Microsoft
// attaches to the fulfillment webhook call: audience checked against this
// publisher's SaaS app registration, issuer/tenant checked against the
// configured Microsoft AAD tenant, signature checked against Microsoft's live
// JWKS (fetched over the network -- this is why the shared EntitlementAdapter
// interface's verifyWebhookSignature is async).

import { createHash } from "node:crypto";
import { createRemoteJWKSet, jwtVerify } from "jose";
import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";
import { applyMarketplaceEntitlementEvent, type MarketplaceAction } from "../marketplace-runtime";

const SAAS_API_BASE = "https://marketplaceapi.microsoft.com/api/saas";
const SAAS_API_VERSION = "2018-08-31";

function requiredEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`REFUSED:MISSING_CONFIG:${name}`);
  return value;
}

/** Real Microsoft Entra ID client-credentials token for this publisher's app registration. */
async function publisherToken(): Promise<string> {
  const tenantId = requiredEnv("MICROSOFT_MARKETPLACE_TENANT_ID");
  const body = new URLSearchParams({
    grant_type: "client_credentials",
    client_id: requiredEnv("MICROSOFT_MARKETPLACE_APP_ID"),
    client_secret: requiredEnv("MICROSOFT_MARKETPLACE_CLIENT_SECRET"),
    scope: "20e940b3-4c77-4b0b-9a53-9e16a1b010a7/.default",
  });
  const response = await fetch(`https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body,
    cache: "no-store",
  });
  const payload = (await response.json().catch(() => ({}))) as { access_token?: string };
  if (!response.ok || !payload.access_token) throw new Error(`BLOCKED:AZURE_TOKEN:${response.status}`);
  return payload.access_token;
}

/** Real EntitlementEvent.action -> real MarketplaceAction, for delegating into marketplace-runtime.ts. */
function toMarketplaceAction(action: EntitlementEvent["action"]): MarketplaceAction {
  return action; // EntitlementEvent's 4 actions are a strict subset of MarketplaceAction's 8.
}

/** Real MarketplaceAction (Azure webhook operation) -> the shared, coarser EntitlementEvent.action. */
function toEntitlementAction(action: string): EntitlementEvent["action"] {
  const normalized = action.toLowerCase();
  const map: Record<string, EntitlementEvent["action"]> = {
    subscribe: "subscribe",
    renew: "subscribe",
    reinstate: "subscribe",
    changeplan: "plan_change",
    changequantity: "plan_change",
    suspend: "suspend",
    unsubscribe: "unsubscribe",
  };
  const found = map[normalized];
  if (!found) throw new Error(`REFUSED:AZURE_ACTION:${action}`);
  return found;
}

export class AzureMarketplaceAdapter implements EntitlementAdapter {
  /**
   * Real AAD bearer-token verification: fetches Microsoft's live JWKS for the
   * configured tenant and cryptographically verifies the webhook's Authorization
   * header against it, checking audience (this app registration) and tenant
   * (`tid` claim). Returns false for any missing/malformed/invalid/expired token
   * rather than throwing, since callers use this as a yes/no gate before trusting
   * the body -- but a genuine configuration gap (no tenant/app id configured)
   * still throws, since "verified false" and "cannot even attempt verification"
   * are not the same failure and must not be conflated into a silent accept-reject.
   */
  async verifyWebhookSignature(rawBody: string, headers: Record<string, string>): Promise<boolean> {
    const authorization = headers.authorization ?? headers.Authorization ?? "";
    if (!authorization.startsWith("Bearer ")) return false;
    const tenantId = requiredEnv("MICROSOFT_MARKETPLACE_TENANT_ID");
    const audience = requiredEnv("MICROSOFT_MARKETPLACE_APP_ID");
    try {
      const verified = await jwtVerify(
        authorization.slice(7),
        createRemoteJWKSet(new URL(`https://login.microsoftonline.com/${tenantId}/discovery/v2.0/keys`)),
        { audience },
      );
      return verified.payload.tid === tenantId;
    } catch {
      return false;
    }
  }

  /**
   * Real parse of the Azure SaaS Fulfillment webhook body's actual JSON shape
   * (subscription/beneficiary/purchaser/offerId/planId/action/timeStamp -- the
   * same field paths lib/marketplace-runtime.ts's parseAzureEvent reads from the
   * live API) into the shared, coarser EntitlementEvent shape. This method's
   * signature (no headers) means it cannot also call the Get Operation API the
   * full runtime path uses to resolve action/offerId when the webhook body omits
   * them, so it reads only what is actually present in `rawBody` itself.
   */
  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    const body = JSON.parse(rawBody) as Record<string, unknown>;
    const subscription = (body.subscription ?? {}) as Record<string, unknown>;
    const beneficiary = (subscription.beneficiary ?? body.beneficiary ?? {}) as Record<string, unknown>;
    const purchaser = (subscription.purchaser ?? body.purchaser ?? {}) as Record<string, unknown>;
    const customerId = String(beneficiary.tenantId ?? purchaser.tenantId ?? body.beneficiaryTenantId ?? "");
    const productId = String(body.offerId ?? subscription.offerId ?? "");
    const planId = String(body.planId ?? subscription.planId ?? "");
    const action = String(body.action ?? "");
    const receivedAt = String(body.timeStamp ?? body.timestamp ?? new Date().toISOString());
    if (!customerId) throw new Error("REFUSED:AZURE_MISSING_BENEFICIARY_TENANT");
    if (!productId) throw new Error("REFUSED:AZURE_MISSING_OFFER_ID");
    return { cloud: "azure", customerId, productId, planId, action: toEntitlementAction(action), receivedAt };
  }

  /**
   * Real List Subscriptions call against the Microsoft SaaS Fulfillment API,
   * filtered to the subscription(s) whose beneficiary tenant matches `customerId`.
   * `EntitlementRecord` carries one (productId, planId, active) triple, so when a
   * tenant holds more than one subscription for this publisher, the most recently
   * updated non-unsubscribed one wins -- the same "single current entitlement per
   * customer" assumption the shared EntitlementRecord shape already bakes in.
   */
  async fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    if (!customerId.trim()) throw new Error("REFUSED:AZURE_CUSTOMER_ID_REQUIRED");
    const token = await publisherToken();
    const response = await fetch(`${SAAS_API_BASE}/subscriptions?api-version=${SAAS_API_VERSION}`, {
      headers: { authorization: `Bearer ${token}` },
      cache: "no-store",
    });
    const payload = (await response.json().catch(() => ({}))) as { subscriptions?: Array<Record<string, unknown>> };
    if (!response.ok) throw new Error(`BLOCKED:AZURE_LIST_SUBSCRIPTIONS:${response.status}`);
    const rows = Array.isArray(payload.subscriptions) ? payload.subscriptions : [];
    const matches = rows.filter((row) => {
      const beneficiary = (row.beneficiary ?? {}) as Record<string, unknown>;
      const purchaser = (row.purchaser ?? {}) as Record<string, unknown>;
      return String(beneficiary.tenantId ?? purchaser.tenantId ?? "") === customerId;
    });
    if (!matches.length) throw new Error(`REFUSED:AZURE_NO_SUBSCRIPTION_FOR_CUSTOMER:${customerId}`);
    matches.sort((a, b) => Date.parse(String(b.lastModified ?? 0)) - Date.parse(String(a.lastModified ?? 0)));
    const selected = matches[0];
    const status = String(selected.saasSubscriptionStatus ?? "").toLowerCase();
    return {
      cloud: "azure",
      customerId,
      productId: String(selected.offerId ?? ""),
      planId: String(selected.planId ?? ""),
      active: status === "subscribed",
    };
  }

  /**
   * Real application: delegates to the already-real, already-tested
   * applyMarketplaceEntitlementEvent (lib/marketplace-runtime.ts) -- the same
   * function app/api/marketplace/[provider]/webhook/route.ts calls -- which
   * resolves the real tenant binding, actuates the real project tier
   * (lib/tiers.ts / lib/k8s.ts setProjectTier) and plan state
   * (lib/plan-state.ts setPlanState), and writes a real, idempotent audit-ledger
   * entry keyed by eventId.
   *
   * EntitlementEvent carries no subscription/agreement id or quantity (the
   * shared cross-cloud shape is coarser than MarketplaceEntitlementEvent), so:
   *   - eventId is a deterministic sha256 of the full event content, giving the
   *     ledger a real, stable idempotency key derived from real event data
   *     (not a random/fabricated value) -- replays of the same event hash to
   *     the same key and are correctly treated as duplicates.
   *   - agreementRef/entitlementRef/subscriptionRef reuse customerId: this
   *     adapter's contract has no separate subscription identifier, and
   *     resolveTenantBinding (marketplace-runtime.ts) looks bindings up by
   *     (provider, buyerRef, productRef) only -- these three columns are
   *     recorded for audit purposes but never used as a lookup key.
   *   - quantity is 1: EntitlementRecord/EntitlementEvent model a single-seat
   *     boolean entitlement (active/not), and quantity is only load-bearing
   *     for the "suspend"/"unsubscribe" actions this event set already excludes
   *     from the >0 quantity check (see marketplace-runtime.ts's validateEvent).
   */
  async applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    if (event.cloud !== "azure") throw new Error(`REFUSED:AZURE_ADAPTER_WRONG_CLOUD:${event.cloud}`);
    const eventId = createHash("sha256")
      .update(JSON.stringify(event), "utf8")
      .digest("hex");
    await applyMarketplaceEntitlementEvent({
      provider: "azure",
      eventId,
      buyerRef: event.customerId,
      productRef: event.productId,
      agreementRef: event.customerId,
      entitlementRef: event.customerId,
      subscriptionRef: event.customerId,
      planRef: event.planId,
      quantity: 1,
      action: toMarketplaceAction(event.action),
      occurredAt: event.receivedAt,
    });
  }
}
