// GENERATED by marketplace-listing-scaffold-pack (ggen). Do not hand-edit.
//
// AzureMarketplaceAdapter -- STUB. Every method below throws or returns a
// placeholder; none call the real AWS SDK yet.
//
// Real SDK package (not yet a dependency of this project): @azure/arm-marketplaceordering
// Real API reference: https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
// Delivery mechanism: push (Fulfillment webhook) as primary; fetchEntitlement calls the Marketplace SaaS Fulfillment API's List Subscriptions operation as reconciliation
// Webhook/SNS endpoint this adapter answers: /api/marketplace/azure/webhook
//
// verifyWebhookSignature for Azure requires validating the AAD (Entra ID) bearer token Microsoft attaches to the fulfillment webhook call (audience/issuer checked against the SaaS app registration), not a body-HMAC scheme -- explicitly the highest-risk unimplemented stub in this pack: a wrong or missing check here means any caller who knows the URL can forge entitlement events.
//
// STILL REQUIRED before this is real (not exhaustive, tracked here so it's
// not silently implied to be done):
//   - Real AWS credentials (IAM role, not a static key) wired via
//     @aws-sdk/credential-providers in this project's deploy environment.
//   - Real SNS topic subscription + subscription confirmation handshake.
//   - A real round trip against the AWS Marketplace SaaS sandbox
//     (resolve-customer, register-usage) has not been run.

import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";

export class AzureMarketplaceAdapter implements EntitlementAdapter {
  verifyWebhookSignature(rawBody: string, headers: Record<string, string>): boolean {
    // TODO(marketplace-listing-scaffold-pack): implement against @azure/arm-marketplaceordering.
    // See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
    throw new Error("AzureMarketplaceAdapter.verifyWebhookSignature is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    // TODO(marketplace-listing-scaffold-pack): implement against @azure/arm-marketplaceordering.
    // See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
    throw new Error("AzureMarketplaceAdapter.parseEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    // TODO(marketplace-listing-scaffold-pack): implement against @azure/arm-marketplaceordering.
    // See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
    throw new Error("AzureMarketplaceAdapter.fetchEntitlement is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    // TODO(marketplace-listing-scaffold-pack): implement against @azure/arm-marketplaceordering.
    // See https://learn.microsoft.com/en-us/partner-center/marketplace-offers/pc-saas-fulfillment-webhook-and-api
    throw new Error("AzureMarketplaceAdapter.applyEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

}
