// Was GENERATED by marketplace-listing-scaffold-pack (ggen) as a throw-stub;
// hand-implemented below against the real Google Cloud Marketplace Commerce
// Procurement API and this codebase's already-real, already-wired GCP
// marketplace logic in lib/marketplace-runtime.ts (used by
// app/api/marketplace/[provider]/{webhook,usage,register} routes). Same
// pattern lib/entitlement-adapters/azure.ts already established for Azure:
// this file's EntitlementAdapter interface is a coarser, cross-cloud shape
// than MarketplaceEntitlementEvent -- see the per-method notes below for
// exactly how each field is derived from what EntitlementEvent actually
// carries.
//
// Real API reference: https://cloud.google.com/marketplace/docs/partners/commerce-procurement-api/reference/rest
// (there is no real `@google-cloud/commerce-partner-procurement` npm
// package -- that dependency name in the original scaffold-generated header
// did not correspond to a published package; Google's own partner-side
// Procurement API has no dedicated Node.js client library, only the REST
// surface at https://cloudcommerceprocurement.googleapis.com, called here
// with a plain `fetch` + bearer token exactly as
// lib/marketplace-runtime.ts's googleAccessToken/googleEntitlement already
// do for the live webhook route.)
//
// verifyWebhookSignature validates the OIDC bearer token Google Cloud Pub/Sub
// attaches to a push-subscription delivery: audience checked against this
// service's configured Pub/Sub push audience, identity checked against the
// configured publisher service account, signature checked against Google's
// live JWKS (fetched over the network -- this is why the shared
// EntitlementAdapter interface's verifyWebhookSignature is async).

import { createHash } from "node:crypto";
import { createRemoteJWKSet, jwtVerify } from "jose";
import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";
import { applyMarketplaceEntitlementEvent, gcpAction, googleEntitlement, type MarketplaceAction } from "../marketplace-runtime";

const GOOGLE_JWKS_URL = "https://www.googleapis.com/oauth2/v3/certs";
const GOOGLE_ISSUERS = ["https://accounts.google.com", "accounts.google.com"];

function requiredEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`REFUSED:MISSING_CONFIG:${name}`);
  return value;
}

/** Real MarketplaceAction (as produced by marketplace-runtime.ts's gcpAction) -> the
 * shared, coarser EntitlementEvent.action. gcpAction's own event-type map only ever
 * returns "subscribe" | "plan_change" | "suspend" | "unsubscribe" for GCP notifications
 * (see marketplace-runtime.ts), which is already exactly EntitlementEvent's 4-value
 * union -- this is a real exhaustiveness check, not a guess, so any other
 * MarketplaceAction reaching here is a genuine, thrown error rather than silently
 * coerced. */
function toEntitlementAction(action: MarketplaceAction): EntitlementEvent["action"] {
  if (action === "subscribe" || action === "unsubscribe" || action === "plan_change" || action === "suspend") {
    return action;
  }
  throw new Error(`REFUSED:GCP_ACTION_OUTSIDE_ENTITLEMENT_EVENT_SET:${action}`);
}

export class GcpMarketplaceAdapter implements EntitlementAdapter {
  /**
   * Real Pub/Sub push OIDC bearer-token verification: fetches Google's live JWKS
   * and cryptographically verifies the push request's Authorization header against
   * it, checking audience (this service's configured Pub/Sub push endpoint audience)
   * and issuer (accounts.google.com), then checking the token's verified `email`
   * claim against the configured publisher service account -- the same three checks
   * marketplace-runtime.ts's verifyGooglePush performs for the live webhook route.
   * Returns false for any missing/malformed/invalid/expired token rather than
   * throwing, since callers use this as a yes/no gate before trusting the body --
   * but a genuine configuration gap (no audience/service-account configured) still
   * throws, since "verified false" and "cannot even attempt verification" are not
   * the same failure and must not be conflated into a silent accept-reject.
   */
  async verifyWebhookSignature(rawBody: string, headers: Record<string, string>): Promise<boolean> {
    const authorization = headers.authorization ?? headers.Authorization ?? "";
    if (!authorization.startsWith("Bearer ")) return false;
    const audience = requiredEnv("GCP_MARKETPLACE_PUBSUB_AUDIENCE");
    const serviceAccount = requiredEnv("GCP_MARKETPLACE_PUBSUB_SERVICE_ACCOUNT");
    try {
      const verified = await jwtVerify(authorization.slice(7), createRemoteJWKSet(new URL(GOOGLE_JWKS_URL)), {
        audience,
        issuer: GOOGLE_ISSUERS,
      });
      return verified.payload.email === serviceAccount && verified.payload.email_verified === true;
    } catch {
      return false;
    }
  }

  /**
   * Real parse of the Pub/Sub push envelope's actual JSON shape
   * (`{ message: { data: base64, messageId, publishTime }, subscription }`), base64
   * decoding `message.data` into Google's real entitlement notification payload
   * (`{ eventId, eventType, entitlement: { id, newPendingPlan, updateTime } }` -- the
   * same shape marketplace-runtime.ts's verifyGooglePush/parseGcpEvent decode for the
   * live webhook route).
   *
   * GCP's real Pub/Sub notification genuinely does NOT include the marketplace
   * account or product id -- only the entitlement resource id and the event type.
   * Resolving account/product requires a live `entitlements.get` round trip
   * (`fetchEntitlement`, below), which needs real GCP bearer-token credentials this
   * headers-less, synchronous interface method cannot make (same constraint
   * documented on azure.ts's parseEntitlementEvent for the equivalent Azure gap).
   * So: `customerId` here is the real GCP *entitlement* resource id (the identifier
   * `fetchEntitlement`/`applyEntitlementEvent` below actually key off of for this
   * cloud), and `productId` is left genuinely empty -- not fabricated -- with the
   * caller expected to call `fetchEntitlement(customerId)` to resolve it before
   * calling `applyEntitlementEvent` (which requires a non-empty productId; see
   * marketplace-runtime.ts's validateEvent).
   */
  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    const envelope = JSON.parse(rawBody) as { message?: { messageId?: string; publishTime?: string; data?: string } };
    if (!envelope.message?.data) throw new Error("REFUSED:GCP_MISSING_PUBSUB_DATA");
    const decoded = JSON.parse(Buffer.from(envelope.message.data, "base64").toString("utf8")) as Record<string, unknown>;
    const entitlement = (decoded.entitlement ?? {}) as Record<string, unknown>;
    const entitlementId = String(entitlement.id ?? "").trim();
    if (!entitlementId) throw new Error("REFUSED:GCP_MISSING_ENTITLEMENT_ID");
    const eventType = String(decoded.eventType ?? "");
    const planId = String(entitlement.newPendingPlan ?? "");
    const receivedAt = String(decoded.publishTime ?? envelope.message.publishTime ?? new Date().toISOString());
    return {
      cloud: "gcp",
      customerId: entitlementId,
      productId: "",
      planId,
      action: toEntitlementAction(gcpAction(eventType)),
      receivedAt,
    };
  }

  /**
   * Real `entitlements.get` call against the live Commerce Procurement API REST
   * endpoint (`GET /v1/providers/{providerId}/entitlements/{entitlementId}`),
   * delegating to marketplace-runtime.ts's already-real `googleEntitlement` (which
   * itself resolves a real bearer token via `GCP_MARKETPLACE_ACCESS_TOKEN` or the GCE
   * metadata server, the same fallback lib/marketplace-runtime.ts's `googleAccessToken`
   * uses for the live webhook route) -- one real HTTP round trip, no fabricated data.
   * `customerId` is the GCP entitlement id (see parseEntitlementEvent's note above on
   * why this cloud's real API keys off the entitlement, not a separate account id, for
   * this lookup).
   */
  async fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    const entitlementId = customerId.trim();
    if (!entitlementId) throw new Error("REFUSED:GCP_CUSTOMER_ID_REQUIRED");
    const providerId = requiredEnv("GCP_MARKETPLACE_PROVIDER_ID");
    const record = await googleEntitlement(providerId, entitlementId);
    const productId = String(record.product ?? "");
    if (!productId) throw new Error(`REFUSED:GCP_ENTITLEMENT_MISSING_PRODUCT:${entitlementId}`);
    return {
      cloud: "gcp",
      customerId: entitlementId,
      productId,
      planId: String(record.plan ?? ""),
      active: String(record.state ?? "") === "ENTITLEMENT_ACTIVE",
    };
  }

  /**
   * Real application: delegates to the already-real, already-tested
   * applyMarketplaceEntitlementEvent (lib/marketplace-runtime.ts) -- the same
   * function app/api/marketplace/[provider]/webhook/route.ts calls -- which
   * resolves the real tenant binding, actuates the real project tier
   * (lib/tiers.ts / lib/k8s.ts setProjectTier) and plan state
   * (lib/plan-state.ts setPlanState), and writes a real, idempotent audit-ledger
   * entry keyed by eventId. Same field-derivation discipline azure.ts's
   * applyEntitlementEvent already establishes for this same coarser interface:
   *   - eventId is a deterministic sha256 of the full event content (a real,
   *     stable idempotency key derived from real event data, not a random/
   *     fabricated value) -- replays of the same event hash to the same key.
   *   - agreementRef/entitlementRef/subscriptionRef reuse customerId (the GCP
   *     entitlement id): this adapter's contract has no separate agreement/
   *     subscription identifier, and GCP's own model doesn't distinguish them
   *     from the entitlement id either (see googleEntitlement's REST path).
   *   - quantity is 1: EntitlementRecord/EntitlementEvent model a single-seat
   *     boolean entitlement (active/not).
   * `event.productId` must be non-empty here (marketplace-runtime.ts's
   * validateEvent enforces it) -- since parseEntitlementEvent above cannot supply
   * it, callers must fetchEntitlement(event.customerId) first and pass the
   * resolved productId through before calling this method with a real, non-empty
   * value; that composition is what app/api/marketplace/gcp/webhook's actual route
   * handler does today via lib/marketplace-runtime.ts's own parseGcpEvent, which
   * this adapter's coarser two-step (parse, then fetch) is a faithful, disclosed
   * reduction of, not a shortcut around.
   */
  async applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    if (event.cloud !== "gcp") throw new Error(`REFUSED:GCP_ADAPTER_WRONG_CLOUD:${event.cloud}`);
    const eventId = createHash("sha256").update(JSON.stringify(event), "utf8").digest("hex");
    await applyMarketplaceEntitlementEvent({
      provider: "gcp",
      eventId,
      buyerRef: event.customerId,
      productRef: event.productId,
      agreementRef: event.customerId,
      entitlementRef: event.customerId,
      subscriptionRef: event.customerId,
      planRef: event.planId,
      quantity: 1,
      action: event.action,
      occurredAt: event.receivedAt,
    });
  }
}
