// GENERATED by marketplace-listing-scaffold-pack (ggen). Do not hand-edit.
//
// GcpMarketplaceAdapter -- STUB. Every method below throws or returns a
// placeholder; none call the real AWS SDK yet.
//
// Real SDK package (not yet a dependency of this project): @google-cloud/commerce-partner-procurement
// Real API reference: https://cloud.google.com/marketplace/docs/partners/integrated-saas/backend-integration
// Delivery mechanism: push (Pub/Sub push subscription delivering Procurement API entitlement.create/entitlement.plan_change/entitlement.delete messages) with fetchEntitlement backed by Procurement API entitlements.list as reconciliation
// Webhook/SNS endpoint this adapter answers: /api/marketplace/gcp/webhook
//
// GCP delivers entitlement changes as Pub/Sub messages, not a raw HTTP webhook -- verifyWebhookSignature here means validating the Pub/Sub push request's OIDC bearer token (aud claim matches this service's configured audience), a third distinct verification mechanism from AWS (SNS signature) and Azure (AAD token audience/issuer).
//
// STILL REQUIRED before this is real (not exhaustive, tracked here so it's
// not silently implied to be done):
//   - Real AWS credentials (IAM role, not a static key) wired via
//     @aws-sdk/credential-providers in this project's deploy environment.
//   - Real SNS topic subscription + subscription confirmation handshake.
//   - A real round trip against the AWS Marketplace SaaS sandbox
//     (resolve-customer, register-usage) has not been run.

import type { EntitlementAdapter, EntitlementEvent, EntitlementRecord } from "../entitlement-adapter";

export class GcpMarketplaceAdapter implements EntitlementAdapter {
  verifyWebhookSignature(rawBody: string, headers: Record<string, string>): boolean {
    // TODO(marketplace-listing-scaffold-pack): implement against @google-cloud/commerce-partner-procurement.
    // See https://cloud.google.com/marketplace/docs/partners/integrated-saas/backend-integration
    throw new Error("GcpMarketplaceAdapter.verifyWebhookSignature is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  parseEntitlementEvent(rawBody: string): EntitlementEvent {
    // TODO(marketplace-listing-scaffold-pack): implement against @google-cloud/commerce-partner-procurement.
    // See https://cloud.google.com/marketplace/docs/partners/integrated-saas/backend-integration
    throw new Error("GcpMarketplaceAdapter.parseEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  fetchEntitlement(customerId: string): Promise<EntitlementRecord> {
    // TODO(marketplace-listing-scaffold-pack): implement against @google-cloud/commerce-partner-procurement.
    // See https://cloud.google.com/marketplace/docs/partners/integrated-saas/backend-integration
    throw new Error("GcpMarketplaceAdapter.fetchEntitlement is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

  applyEntitlementEvent(event: EntitlementEvent): Promise<void> {
    // TODO(marketplace-listing-scaffold-pack): implement against @google-cloud/commerce-partner-procurement.
    // See https://cloud.google.com/marketplace/docs/partners/integrated-saas/backend-integration
    throw new Error("GcpMarketplaceAdapter.applyEntitlementEvent is not implemented -- stub generated by marketplace-listing-scaffold-pack");
  }

}
