"""Receipt chain in git (post-tag): the parent is read from committed bytes, never from a
90-day Actions artifact.

``release/<v>/hardening/receipts/chain.json`` (GENERATED by ``hardening.py``) orders the
committed crown receipts under ``hardening/receipts/run-*/crown-receipt.json`` by their
``previous_receipt_digest`` links. The parent of a post-tag attestation is the chain head.
It is admitted only when every entry's bytes recompute to its recorded digest and the
links are unbroken (``PARENT_DIGEST``), the parent is not REFUSED (``PARENT_REFUSED``),
a BLOCKED parent carries only typed remaining items (``PARENT_UNTYPED_BLOCKED``), and the
parent's crown SHA is an ancestor of the attested head (``PARENT_NOT_ANCESTOR``); each is
``REFUSED:RECEIPT_CHAIN_BROKEN:<token>``. Ancestry is supplied as data (``git rev-list``
output written outside the court); absent ancestry is a typed blocker, never a pass.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .model import FAILURE_CLASS

CHAIN_FILE = "receipts/chain.json"
SCHEMA_CHAIN = "https://chatman.dev/root-crown/hardening/chain/v1"


def _digest_of(receipt: dict[str, Any]) -> str:
    from .crown import receipt_digest_of  # local import: crown imports chain

    return receipt_digest_of(receipt)


def committed_receipts(hardening_dir: Path) -> dict[str, tuple[str, dict[str, Any]]]:
    """receipt_digest -> (hardening-relative path, receipt) for every committed run receipt."""
    out: dict[str, tuple[str, dict[str, Any]]] = {}
    for path in sorted((hardening_dir / "receipts").glob("run-*/crown-receipt.json")):
        receipt = json.loads(path.read_text(encoding="utf-8"))
        out[str(receipt.get("receipt_digest"))] = (path.relative_to(hardening_dir).as_posix(), receipt)
    return out


def order(hardening_dir: Path) -> list[dict[str, Any]]:
    """Entries ordered by previous_receipt_digest links (first = the one whose parent is outside)."""
    receipts = committed_receipts(hardening_dir)
    children: dict[str | None, list[str]] = {}
    for dig, (_, receipt) in receipts.items():
        prev = receipt.get("previous_receipt_digest")
        children.setdefault(prev if prev in receipts else None, []).append(dig)
    ordered: list[str] = []
    frontier = sorted(children.get(None, []))
    while frontier:
        dig = frontier.pop(0)
        ordered.append(dig)
        frontier = sorted(children.get(dig, [])) + frontier
    entries = []
    for dig in ordered:
        path, receipt = receipts[dig]
        entries.append(
            {
                "path": path,
                "run_id": path.split("/")[1].removeprefix("run-"),
                "receipt_digest": dig,
                "previous_receipt_digest": receipt.get("previous_receipt_digest"),
                "standing": receipt.get("standing"),
                "crown_sha": receipt.get("crown_sha"),
                "genesis": bool(receipt.get("genesis")),
            }
        )
    return entries


def project(hardening_dir: Path, release: str) -> dict[str, Any]:
    entries = order(hardening_dir)
    return {
        "GENERATED": "scripts/release_train/root_crown/hardening.py -- do not edit; run --write",
        "schema": SCHEMA_CHAIN,
        "release": release,
        "entries": entries,
        "head": entries[-1]["receipt_digest"] if entries else None,
    }


def _untyped(receipt: dict[str, Any]) -> list[str]:
    bad = []
    for item in receipt.get("remaining", []):
        code = item.get("code")
        if not code or code not in FAILURE_CLASS or not item.get("failure_class") or not item.get("broken_term"):
            bad.append(f"{item.get('id')}:{code}")
    return bad


@dataclass
class ChainResult:
    parent: dict[str, Any] | None
    refusals: list[str] = field(default_factory=list)
    blockers: list[str] = field(default_factory=list)

    @property
    def parent_digest(self) -> str | None:
        return None if self.parent is None else self.parent.get("receipt_digest")


def parent_of(hardening_dir: Path, ancestry: set[str] | None) -> ChainResult:
    path = hardening_dir / CHAIN_FILE
    if not path.is_file():
        return ChainResult(None, [f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:{CHAIN_FILE} absent"])
    doc = json.loads(path.read_text(encoding="utf-8"))
    entries = doc.get("entries") or []
    if not entries or doc.get("head") != entries[-1].get("receipt_digest"):
        return ChainResult(None, ["REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:chain head is not the last entry"])
    refusals: list[str] = []
    receipts: dict[str, dict[str, Any]] = {}
    previous: str | None = None
    for i, entry in enumerate(entries):
        file = hardening_dir / str(entry.get("path"))
        if not file.is_file():
            refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:{entry.get('path')} absent")
            continue
        receipt = json.loads(file.read_text(encoding="utf-8"))
        recomputed = _digest_of(receipt)
        if recomputed != receipt.get("receipt_digest") or recomputed != entry.get("receipt_digest"):
            refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:{entry.get('path')}:recomputed={recomputed}")
        if i > 0 and receipt.get("previous_receipt_digest") != previous:
            refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:{entry.get('path')}:link")
        previous = entry.get("receipt_digest")
        receipts[str(entry.get("receipt_digest"))] = receipt
    parent = receipts.get(str(doc["head"]))
    if refusals or parent is None:
        return ChainResult(None, refusals or ["REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_DIGEST:head unreadable"])
    blockers: list[str] = []
    if parent.get("standing") == "REFUSED":
        refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_REFUSED:{doc['head']}")
    elif parent.get("standing") == "BLOCKED" and _untyped(parent):
        refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_UNTYPED_BLOCKED:{','.join(_untyped(parent)[:5])}")
    if ancestry is None:
        blockers.append("BLOCKED:OBSERVATION_MISSING:parent ancestry unobserved (no --ancestry)")
    elif parent.get("crown_sha") not in ancestry:
        refusals.append(f"REFUSED:RECEIPT_CHAIN_BROKEN:PARENT_NOT_ANCESTOR:{parent.get('crown_sha')}")
    return ChainResult(parent if not refusals else None, refusals, blockers)
