"""Deterministic projector for release/v26.9.25 (stdlib only, no network).

Inputs (hand-written sources of truth): requirements.json, pins.json, closure.json,
worktrees-allow.json, imports/RFC-0004.md, imports/IMPORTS.json, and the previously
committed berthier.json (its compile baseline).

Outputs (GENERATED, never hand-edited): manifest.toml (verify_release.py compatible),
berthier.json, out/packets.json, out/requirements.ttl. ``--check`` re-projects and
refuses ``REFUSED:PROJECTION_DRIFT:<path>`` on any byte difference.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from scripts import release_line  # type: ignore[attr-defined]
from scripts import verify_release  # type: ignore[attr-defined]
from scripts.release_train.release_closure_court.court import evaluate as closure_evaluate

from . import berthier
from .model import Requirement, sha256_bytes
from .requirements import load_rows, to_requirement

GENERATED = ("manifest.toml", "berthier.json", "out/packets.json", "out/requirements.ttl")
INPUTS = (
    "requirements.json",
    "pins.json",
    "closure.json",
    "worktrees-allow.json",
    "imports/RFC-0004.md",
    "imports/IMPORTS.json",
)
HEADER = (
    "# GENERATED by scripts/release_train/root_crown/projector.py -- do not edit; edit the inputs and run --write.\n"
)
_IMPL_TO_COMPONENT = {
    "ALIVE": "ALIVE",
    "PARTIAL_ALIVE": "PARTIAL_ALIVE",
    "BLOCKED": "BLOCKED",
    "REFUSED": "BLOCKED",
    "UNSUPPORTED": "BLOCKED",
    "PLANNED": "UNKNOWN",
    "NOT_CLAIMED": "UNKNOWN",
    "SUPERSEDED": "UNKNOWN",
}


@dataclass(frozen=True)
class Inputs:
    release_dir: Path
    version: str
    requirements_doc: dict[str, Any]
    requirements: tuple[Requirement, ...]
    pins: dict[str, Any]
    closure: dict[str, Any]
    allow: dict[str, Any]
    rfc_text: str
    imports: dict[str, Any]
    prior_berthier: dict[str, Any] | None
    input_digests: dict[str, str]


def load_inputs(release_dir: Path) -> Inputs:
    missing = [name for name in INPUTS if not (release_dir / name).is_file()]
    if missing:
        raise FileNotFoundError(",".join(f"REFUSED:PROJECTION_INPUT_MISSING:{m}" for m in missing))
    doc = load_rows(release_dir / "requirements.json")
    prior_path = release_dir / "berthier.json"
    return Inputs(
        release_dir=release_dir,
        version=release_dir.name,
        requirements_doc=doc,
        requirements=tuple(to_requirement(r) for r in doc["requirements"]),
        pins=json.loads((release_dir / "pins.json").read_text(encoding="utf-8")),
        closure=json.loads((release_dir / "closure.json").read_text(encoding="utf-8")),
        allow=json.loads((release_dir / "worktrees-allow.json").read_text(encoding="utf-8")),
        rfc_text=(release_dir / "imports/RFC-0004.md").read_text(encoding="utf-8"),
        imports=json.loads((release_dir / "imports/IMPORTS.json").read_text(encoding="utf-8")),
        prior_berthier=json.loads(prior_path.read_text(encoding="utf-8")) if prior_path.is_file() else None,
        input_digests={name: sha256_bytes((release_dir / name).read_bytes()) for name in INPUTS},
    )


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    raise TypeError(f"unsupported TOML value {value!r}")


def _toml_table(name: str, table: dict[str, Any], array: bool = False) -> str:
    head = f"[[{name}]]" if array else f"[{name}]"
    return head + "\n" + "".join(f"{k} = {_toml_value(v)}\n" for k, v in table.items())


def manifest_data(inputs: Inputs) -> dict[str, Any]:
    impl_by_repo: dict[str, str] = {}
    for row in inputs.closure.get("subjects", []):
        if row.get("spec_standing") == "NOT_A_SPEC":
            impl_by_repo[row.get("repository")] = row.get("impl_standing", "UNKNOWN")
    components = []
    observations = []
    for key, pin in sorted(inputs.pins["repos"].items()):
        if pin.get("root"):
            continue
        components.append(
            {
                "id": key,
                "repository": pin["repository"],
                "ref": pin["ref"],
                "ref_check": pin.get("ref_check", "github"),
                "sha": pin["sha"],
                "role": pin["role"],
                "disposition": pin["disposition"],
                "standing": _IMPL_TO_COMPONENT.get(impl_by_repo.get(pin["repository"], ""), "UNKNOWN"),
                "required": bool(pin["required"]),
                "depends_on": list(pin.get("depends_on", [])),
            }
        )
        if pin.get("ref_check") == "external":
            observations.append(
                {
                    "component": key,
                    "repository": pin["repository"],
                    "ref": pin["ref"],
                    "sha": pin["sha"],
                    "authority": inputs.pins["authority"],
                    "observed_at": inputs.pins["observed_at"],
                }
            )
    release = {
        "name": "Chatman Ecosystem",
        "version": inputs.version[1:],
        "root_repository": inputs.pins["root_repository"],
        "standing": "UNKNOWN",
        "premise": f"{inputs.imports['imports'][0]['source_repo']}:RFC-0004@{inputs.imports['imports'][0]['source_sha']}",
        "closure_standing": closure_evaluate(inputs.closure).standing,
        "required_roles": sorted({c["role"] for c in components if c["required"]}),
    }
    data = {"release": release, "components": components}
    if observations:
        data["external_ref_observations"] = observations
    findings = verify_release.validate_manifest(data, expected_version=inputs.version)
    release["standing"] = verify_release.crown_standing(data, findings)
    return data


def render_manifest(inputs: Inputs, data: dict[str, Any]) -> bytes:
    parts = [HEADER]
    parts.append("# inputs: " + ", ".join(f"{k}={v[:16]}" for k, v in sorted(inputs.input_digests.items())) + "\n\n")
    parts.append(_toml_table("release", data["release"]))
    for component in data["components"]:
        parts.append("\n" + _toml_table("components", component, array=True))
    for observation in data.get("external_ref_observations", []):
        parts.append("\n" + _toml_table("external_ref_observations", observation, array=True))
    return "".join(parts).encode("utf-8")


def _ttl_literal(text: str) -> str:
    return json.dumps(text, ensure_ascii=True)


def render_ttl(inputs: Inputs) -> bytes:
    lines = [
        "# GENERATED by scripts/release_train/root_crown/projector.py -- one-way view; requirements.json is the source.",
        "@prefix rc: <https://chatman.dev/root-crown#> .",
        "@prefix dcterms: <http://purl.org/dc/terms/> .",
        "",
        f"rc:{inputs.version.replace('.', '_')} a rc:Release ;",
        f"  rc:premise {_ttl_literal(inputs.requirements_doc['premise']['rfc_id'])} .",
        "",
    ]
    for req in inputs.requirements:
        node = "rc:" + req.id.replace("-", "_")
        lines.append(f"{node} a rc:{'AcceptanceCriterion' if req.kind == 'AC' else 'Falsifier'} ;")
        lines.append(f"  dcterms:identifier {_ttl_literal(req.id)} ;")
        lines.append(f"  rc:term {_ttl_literal(req.term)} ;")
        lines.append(f"  rc:owner {_ttl_literal(req.owner_repo)} ;")
        lines.append(f"  rc:evidenceKind {_ttl_literal(req.evidence_kind)} ;")
        lines.append(f"  rc:evidenceLocator {_ttl_literal(req.evidence_locator)} ;")
        for ref in req.premise_refs:
            lines.append(f"  rc:premiseRef {_ttl_literal(ref)} ;")
        for dep in req.depends_on:
            lines.append(f"  rc:dependsOn rc:{dep.replace('-', '_')} ;")
        lines.append(f"  rc:acceptance {_ttl_literal(req.acceptance)} .")
        lines.append("")
    return ("\n".join(lines)).encode("utf-8")


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("utf-8")


def compile_graph(inputs: Inputs, rfc_text: str | None = None) -> dict[str, bytes]:
    """Project the Berthier graph, packets and the TTL view (premise text overridable in memory)."""
    text = inputs.rfc_text if rfc_text is None else rfc_text
    reqs = inputs.requirements
    sources = berthier.source_digests(text, reqs)
    prior = inputs.prior_berthier
    prior_edges = berthier.edges_from_json(prior["edges"]) if prior else ()
    if prior is None:
        baseline: dict[str, str] = {}
    elif prior.get("compiled") == sources:
        baseline = dict(prior.get("baseline", {}))
    else:
        baseline = dict(prior.get("compiled", {}))
    # Impact and packets from the strategic delta baseline -> sources.
    probe = berthier.build_edges(reqs, sources, {})
    changed = berthier.delta(baseline, sources)
    impact = berthier.impact_of(probe, changed)
    packet_list = berthier.packets(reqs, impact, changed, inputs.pins)
    packets_doc = {
        "release": inputs.version,
        "premise": berthier.PREMISE,
        "strategic_delta": list(changed),
        "packets": packet_list,
    }
    packets_bytes = _json_bytes(packets_doc)
    ttl_bytes = render_ttl(inputs)
    consumer = {
        "proj:out/packets.json": sha256_bytes(packets_bytes),
        "proj:out/requirements.ttl": sha256_bytes(ttl_bytes),
    }
    for packet in packet_list:
        consumer[berthier.packet_key(packet["subject"]["repository"])] = sha256_bytes(_json_bytes(packet))
    fresh = berthier.build_edges(reqs, sources, consumer)
    by_pair = {(e.producer.key, e.consumer.key): e for e in prior_edges}
    edges = []
    for edge in fresh:
        old = by_pair.get((edge.producer.key, edge.consumer.key))
        if old is not None and old.compiled_from != edge.compiled_from:
            edge = berthier.renew_projection(old, edge.compiled_from, edge.consumer_digest)
        edges.append(edge)
    graph = berthier.graph_document(tuple(edges), baseline, sources)
    return {
        "berthier.json": _json_bytes(graph),
        "out/packets.json": packets_bytes,
        "out/requirements.ttl": ttl_bytes,
    }


def project(inputs: Inputs) -> dict[str, bytes]:
    outputs = compile_graph(inputs)
    outputs["manifest.toml"] = render_manifest(inputs, manifest_data(inputs))
    return dict(sorted(outputs.items()))


def check(release_dir: Path) -> list[str]:
    try:
        inputs = load_inputs(release_dir)
    except FileNotFoundError as exc:
        return str(exc).split(",")
    refusals = []
    for name, content in project(inputs).items():
        path = release_dir / name
        if not path.is_file() or path.read_bytes() != content:
            refusals.append(f"REFUSED:PROJECTION_DRIFT:{name}")
    return refusals


def write(release_dir: Path) -> dict[str, bytes]:
    outputs = project(load_inputs(release_dir))
    for name, content in outputs.items():
        path = release_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="root_crown.projector")
    parser.add_argument("--release", required=True)
    parser.add_argument("--root", type=Path, default=Path("."))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    try:
        release_dir = args.root / release_line.release_dir(args.release)
    except release_line.ReleaseLineError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    if args.write:
        for name, content in write(release_dir).items():
            print(f"wrote {release_dir / name} sha256={sha256_bytes(content)}")
        return 0
    refusals = check(release_dir)
    for refusal in refusals:
        print(refusal)
    if refusals:
        return 2
    print(f"PROJECTION_CURRENT:{release_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
