from enum import Enum

class Strategy(str, Enum):
    MAX_INFORMATION_GAIN = "MAX_INFORMATION_GAIN"
    MAX_INFORMATION_PER_COST = "MAX_INFORMATION_PER_COST"
    MIN_EXPECTED_ENTROPY = "MIN_EXPECTED_ENTROPY"
