// GENERATED by marketplace-listing-scaffold-pack (ggen). Do not hand-edit --
// re-run `ggen sync run` after editing ontology.ttl instead.
//
// Generic entitlement-adapter contract shared by every cloud marketplace
// integration (AWS/Azure/GCP). Each cloud's concrete adapter
// (app/lib/entitlement-adapters/{aws,azure,gcp}.ts) implements this
// interface. NONE of the concrete adapters are wired to real SDK calls yet
// -- see each adapter file's header for exactly what is stubbed.

export interface EntitlementEvent {
  cloud: "aws" | "azure" | "gcp";
  customerId: string;
  productId: string;
  planId: string;
  action: "subscribe" | "unsubscribe" | "plan_change" | "suspend";
  receivedAt: string;
}

export interface EntitlementRecord {
  cloud: "aws" | "azure" | "gcp";
  customerId: string;
  productId: string;
  planId: string;
  active: boolean;
}

export interface EntitlementAdapter {
  /**
   * Verify the inbound entitlement/subscription webhook actually came from this cloud's
   * marketplace, not a forged caller. Async because every real cloud verification scheme
   * (AWS SNS cert fetch + RSA verify, Azure AAD JWKS fetch + JWT verify, GCP Pub/Sub OIDC
   * JWKS fetch + JWT verify) requires a network round trip to fetch the current signing
   * key(s) -- none of them can be checked synchronously against a fixed local secret.
   */
  verifyWebhookSignature(rawBody: string, headers: Record<string, string>): Promise<boolean>;
  /** Parse the cloud-specific webhook payload into the shared EntitlementEvent shape. */
  parseEntitlementEvent(rawBody: string): EntitlementEvent;
  /** Poll/fetch the current entitlement record for a customer directly from the cloud SDK (needed where the cloud does not push webhooks reliably). */
  fetchEntitlement(customerId: string): Promise<EntitlementRecord>;
  /** Apply a parsed entitlement event to platform-console's own tier/quota state (app/lib/tiers.ts, app/lib/quota-enforcement.ts). */
  applyEntitlementEvent(event: EntitlementEvent): Promise<void>;
}
