#!/usr/bin/env python3
"""Lift a consumer's hand-assembled reference orders (orders.json) into nlb:ReferenceOrder facts.

nonllm-class-qualification-pack 0.1.0. A reference order is candidate design capital (O): the lift
records it so that "the generated qualification plan covers every reference order" is a graph
property a court can check. It never creates an sj:WorkOrder.

Usage:
  lift_reference_orders.py --consumer DIR            write <out> from <source> (bench.toml [lift])
  lift_reference_orders.py --consumer DIR --check    exit 0 iff the committed <out> equals the lift

Deterministic: one Turtle document, subjects in orders.json order, literals escaped per Turtle 1.1
ECHAR/UCHAR rules; the header names the source sha256 and this script's sha256.
Exit: 0 ok; 1 drift or invalid source (REFUSED lines); 2 usage.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from pathlib import Path

NLB = "https://ggen.dev/nonllm-bench#"
PROV = "http://www.w3.org/ns/prov#"
RDFS = "http://www.w3.org/2000/01/rdf-schema#"
FIELDS = (
    ("referenceId", "id"),
    ("referenceRepo", "repo"),
    ("referenceRequirement", "requirement"),
    ("referenceTask", "task"),
    ("referenceGate", "gate"),
    ("referenceFalsifier", "falsifier"),
)


def turtle_string(value: str) -> str:
    out = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif code < 0x20 or code == 0x7F:
            out.append(f"\\u{code:04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def lift(consumer: Path) -> tuple[Path, str]:
    config = tomllib.loads((consumer / "bench.toml").read_text(encoding="utf-8"))["lift"]
    source = consumer / config["source"]
    namespace = config["namespace"]
    traces: dict[str, list[str]] = config.get("trace", {})
    data = json.loads(source.read_text(encoding="utf-8"))
    orders = data.get("orders")
    if not isinstance(orders, list) or not orders:
        raise ValueError(f"{source}: no orders list")
    lines = [
        "# GENERATED by nonllm-class-qualification-pack scripts/lift_reference_orders.py; do not edit.",
        f"# source: {config['source']} sha256:{sha256_file(source)}",
        f"# lift: scripts/lift_reference_orders.py sha256:{sha256_file(Path(__file__).resolve())}",
        f"# {len(orders)} reference orders (candidate design capital, O); none is a work order.",
        "",
    ]
    seen: set[str] = set()
    for order in orders:
        oid = order.get("id")
        if not isinstance(oid, str) or not oid or oid in seen:
            raise ValueError(f"{source}: missing or duplicate order id {oid!r}")
        seen.add(oid)
        requirement = order.get("requirement", "")
        if requirement not in traces:
            raise ValueError(f"{source}: {oid} requirement {requirement!r} has no [lift.trace] row")
        subject = f"<{namespace}ref-{oid}>"
        lines.append(f"{subject} a <{NLB}ReferenceOrder> ;")
        lines.append(f"    <{RDFS}label> {turtle_string(oid + ' (reference order)')} ;")
        for prop, key in FIELDS:
            value = order.get(key)
            if not isinstance(value, str) or not value:
                raise ValueError(f"{source}: {oid} has no string field {key!r}")
            lines.append(f"    <{NLB}{prop}> {turtle_string(value)} ;")
        for dep in order.get("depends_on", []):
            lines.append(f"    <{NLB}referenceDependsOn> {turtle_string(dep)} ;")
        derived = " , ".join(f"<{iri}>" for iri in traces[requirement])
        lines.append(f"    <{PROV}wasDerivedFrom> {derived} .")
        lines.append("")
    return consumer / config["out"], "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--consumer", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        out, text = lift(args.consumer)
    except (ValueError, KeyError, OSError, json.JSONDecodeError) as exc:
        print(f"REFUSED[lift_invalid] {exc}")
        return 1
    if args.check:
        if not out.is_file() or out.read_text(encoding="utf-8") != text:
            print(f"REFUSED[lift_drift] {out} differs from the lift of its source")
            return 1
        print(f"LIFT OK {out} ({text.count(' a <' + NLB + 'ReferenceOrder>')} reference orders)")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"LIFT WROTE {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
