"""Release scorecard: real measures over literal trees, real projection over committed inputs.

Chicago style: every assertion runs the real measure / projection functions on real bytes
(literal file contents or the committed observation, closure-final and matrix) and checks the
returned values; no collaborator is replaced.
"""

from __future__ import annotations

import copy
import json
import unittest
from pathlib import Path

from scripts.release_train.scorecard import measure, project

REPO = Path(__file__).resolve().parents[3]
RELEASE = "v26.9.25"
HARDENING = REPO / "release" / RELEASE / "hardening"
OBSERVATION = HARDENING / "inputs" / "scorecard-observations.json"
GENERATED = "scripts/release_train/root_crown/hardening.py -- do not edit; run --write"


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


class MeasureTest(unittest.TestCase):
    def test_text_loc_and_binary(self):
        self.assertEqual(measure.loc_of("a\n\n  \nb\n"), 2)
        self.assertIsNone(measure.text_of(b"\x00\x01binary"))
        self.assertIsNone(measure.text_of(b"\xff\xfe not utf8"))
        self.assertEqual(measure.text_of(b"ok\n"), "ok\n")

    def test_each_generated_marker_counts_only_in_the_header(self):
        for marker in (b"GENERATED by", b"Generated by ggen", b"@generated", b"DO NOT EDIT"):
            with self.subTest(marker=marker):
                self.assertTrue(measure.is_generated(b"# " + marker + b"\nx = 1\n"))
        late = b"x\n" * (measure.HEADER_BYTES // 2 + 10) + b"# DO NOT EDIT\n"
        self.assertFalse(measure.is_generated(late))
        self.assertFalse(measure.is_generated(b"# generated by hand (lowercase is not a marker)\n"))

    def test_tree_summary_counts_generated_handwritten_and_reuse(self):
        tree = measure.TreeMeasure()
        tree.add("gen/a.py", b"# Generated by ggen\nx = 1\ny = 2\n")
        tree.add("src/b.py", b"a\nb\nc\nd\ne\n")
        tree.add("src/c.py", b"one\n")
        tree.add("img.png", b"\x89PNG\x00\x00")
        tree.add(
            "HANDWRITTEN.md",
            b"# ledger\n\nFormat: `path | element | gap | owner | date`\n\n"
            b"src/b.py, src/{c,d}.py (note: d absent) | e | gap | owner | 2026-09-25\n",
        )
        blobs = {measure.blob_sha(b"a\nb\nc\nd\ne\n")}
        s = tree.summary(blobs)
        self.assertEqual((s["files"], s["text_files"]), (5, 4))
        self.assertEqual((s["generated_files"], s["generated_loc"]), (1, 3))
        self.assertEqual(s["handwritten"]["matched_files"], 2)
        self.assertEqual(s["handwritten"]["loc"], 6)
        self.assertEqual(s["handwritten"]["unmatched_entries"], ["HANDWRITTEN.md:src/d.py"])
        self.assertEqual((s["marketplace_reused_files"], s["marketplace_reused_loc"]), (1, 5))
        self.assertIsNone(tree.summary(None)["marketplace_reused_loc"])

    def test_ledger_globs_directories_and_nested_base(self):
        paths = {"pkg/HANDWRITTEN.md", "pkg/a/x.sh", "pkg/a/y.sh", "pkg/dir/one.py", "top/z.py"}
        entries = measure.ledger_entries("a/*.sh | e\ndir/ | e\ntop/z.py | e\n")
        hit, miss = measure.match_entries(entries, paths, "pkg/")
        self.assertEqual(hit, {"pkg/a/x.sh", "pkg/a/y.sh", "pkg/dir/one.py"})
        self.assertEqual(miss, ["top/z.py"])
        tree = measure.TreeMeasure()
        for p in sorted(paths):
            tree.add(p, b"a|b\n" if p.endswith(".md") else b"line\n")
        tree.ledgers["pkg/HANDWRITTEN.md"] = "a/*.sh | e\ndir/ | e\ntop/z.py | e\n"
        self.assertEqual(tree.summary(None)["handwritten"]["matched_files"], 4)

    def test_duplicated_lines_counts_a_planted_window_and_not_a_singleton(self):
        block = [f"value_{i} = compute({i})" for i in range(measure.WINDOW)]
        base = {"r:a.py": block + ["unique_a()"], "r:b.py": ["unique_b()"]}
        clean = measure.duplicated_lines(base)
        self.assertEqual(clean["duplicated_loc"], 0)
        planted = dict(base, **{"r:b.py": ["unique_b()"] + ["  " + line + "  " for line in block]})
        dup = measure.duplicated_lines(planted)
        self.assertEqual(dup["duplicated_loc"], 2 * measure.WINDOW)
        self.assertEqual(dup["top_clusters"][0]["locations"], ["r:a.py", "r:b.py"])

    def test_punctuation_lines_do_not_form_windows(self):
        braces = ["}", "{", ");", "", "]"] * 4
        self.assertEqual(measure.duplicated_lines({"x": braces, "y": braces})["duplicated_loc"], 0)


@unittest.skipUnless(OBSERVATION.is_file(), "scorecard observation not committed")
class ProjectionTest(unittest.TestCase):
    def setUp(self):
        self.obs = load(OBSERVATION)
        self.closure = load(HARDENING / "closure-final.json")
        self.matrix = load(HARDENING / "requirements-matrix.json")

    def test_committed_scorecard_and_benchmark_are_the_projection(self):
        edges_path = REPO / "release" / RELEASE / "autonomy" / "edges.json"
        edges = load(edges_path) if edges_path.is_file() else None
        rendered = project.scorecard(self.obs, self.closure, self.matrix, edges, GENERATED)
        self.assertEqual(load(HARDENING / "scorecard.json"), json.loads(json.dumps(rendered)))
        self.assertEqual(load(HARDENING / "benchmark.json"), json.loads(json.dumps(project.benchmark(self.obs, GENERATED))))

    def test_every_metric_has_definition_falsifier_and_standing(self):
        card = project.scorecard(self.obs, self.closure, self.matrix, None, GENERATED)
        ids = [m["id"] for m in card["metrics"]]
        self.assertEqual(ids, [f"SC-{i:02d}" for i in range(1, 12)])
        for m in card["metrics"]:
            with self.subTest(metric=m["id"]):
                self.assertTrue(m["definition"].strip() and m["falsifier"].strip())
                self.assertRegex(m["standing"], r"^(ALIVE|PARTIAL_ALIVE|UNKNOWN|UNSUPPORTED)")
        self.assertEqual(card["hypervolume"]["standing"], "UNSUPPORTED(no admitted ordering)")

    def test_edges_absent_is_typed_unknown_and_present_is_counted(self):
        absent = project.scorecard(self.obs, self.closure, self.matrix, None, GENERATED)["metrics"][-1]
        self.assertIsNone(absent["value"])
        self.assertTrue(absent["standing"].startswith("UNKNOWN(") and "edges.json absent" in absent["standing"])
        edges = {"edges": [{"id": "E1", "status": "RETIRED"}, {"id": "E2", "status": "HUMAN"}]}
        present = project.scorecard(self.obs, self.closure, self.matrix, edges, GENERATED)["metrics"][-1]
        self.assertEqual((present["value"], present["standing"], present["edges"]), (1, "ALIVE", 2))

    def test_a_survivor_lowers_the_kill_ratio_and_an_error_downgrades_coverage(self):
        base = project.metrics(self.obs, self.closure, self.matrix, None)[4]
        self.assertEqual(base["id"], "SC-05")
        self.assertEqual(base["value"], 1.0)
        obs = copy.deepcopy(self.obs)
        obs["mutation_harnesses"][0]["killed"] -= 1
        self.assertLess(project.metrics(obs, self.closure, self.matrix, None)[4]["value"], 1.0)
        obs["mutation_harnesses"][1]["error"] = "REFUSED[PATH_NOT_FOUND] x"
        self.assertEqual(project.metrics(obs, self.closure, self.matrix, None)[4]["standing"], "PARTIAL_ALIVE")

    def test_benchmark_delta_is_the_difference_of_its_rows(self):
        bench = project.benchmark(self.obs, GENERATED)
        paired = [r for r in bench["rows"] if "delta" in r]
        self.assertEqual(len(paired), bench["paired_repositories"])
        self.assertGreater(len(paired), 0)
        for row in paired:
            for field, delta in row["delta"].items():
                self.assertEqual(delta, (row[RELEASE][field] or 0) - (row["v26.9.24"][field] or 0))

    def test_unmeasured_repository_is_unknown_not_zero(self):
        obs = copy.deepcopy(self.obs)
        repo = sorted(obs["releases"][RELEASE]["repos"])[0]
        obs["releases"][RELEASE]["repos"][repo]["error"] = "ARCHIVE_FAILED:x"
        first = project.metrics(obs, self.closure, self.matrix, None)[0]
        self.assertEqual(first["standing"], "PARTIAL_ALIVE")
        self.assertIn(repo, first["repos_unmeasured"])
        row = next(r for r in project.benchmark(obs, GENERATED)["rows"] if r["repository"] == repo)
        self.assertTrue(row[RELEASE]["standing"].startswith("UNKNOWN(ARCHIVE_FAILED"))


if __name__ == "__main__":
    unittest.main()
