from .errors import Refused
REQUIRED={"DISCOVERY","CONFORMANCE","SIMULATION","PREDICTION","OPTIMIZATION","INTERVENTION","MONITORING","EVENT_CENTRIC","OBJECT_CENTRIC","DECLARATIVE","PROCEDURAL"}
def require(kinds):
    if REQUIRED-set(kinds): raise Refused("REFUSED[INCOMPLETE_METHODOLOGY_COVERAGE]")
    return True
