#!/usr/bin/env python3
"""Regenerate a dated stub/WIP audit under docs/audits/.

Scans the tracked tree (via `git ls-files`) for stub/WIP markers
(TODO, FIXME, XXX, `unimplemented!`, `todo!`, `stub!`) in source and doc
files, and for any placeholder/mock test doubles banned by
AGENTS.md rule 9 (`unittest.mock`, `MagicMock`, `jest.mock`).

This closes the gap identified in the 2026-08 ERRC pass: docs/audits/ had a
single, now-stale audit (2026-08-08-stubs-wip.md, recorded when the tree held
only .gitignore and LICENSE) with no recurring mechanism to re-run it against
the grown implementation surface. Running this script and committing its
output is the recurring-audit cadence; it does not run itself on a schedule.

Usage:
    python3 scripts/audit_stubs_wip.py [--write]

Without --write, prints the findings to stdout. With --write, creates
docs/audits/<YYYY-MM-DD>-stubs-wip.md from the current tree.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

MARKER_PATTERN = re.compile(
    r"\b(TODO|FIXME|XXX)\b|unimplemented!\s*\(|todo!\s*\(|stub!\s*\("
)
MOCK_PATTERN = re.compile(
    r"unittest\.mock|MagicMock\(|Mock\(\)|jest\.mock\(|monkeypatch\."
)

# File suffixes worth scanning for stub markers.
SOURCE_SUFFIXES = {".rs", ".py", ".ts", ".tsx", ".js", ".toml"}
# This script's own module and the audit doc it writes describe the pattern
# deliberately, not as a stub marker in code; exclude self and audits dir.
EXCLUDE_PATHS = {"scripts/audit_stubs_wip.py"}
EXCLUDE_DIRS = {"docs/audits/"}


def tracked_files() -> list[str]:
    output = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, check=True, text=True
    ).stdout
    return [line for line in output.splitlines() if line]


def scan() -> tuple[list[tuple[str, int, str]], list[tuple[str, int, str]]]:
    markers: list[tuple[str, int, str]] = []
    mock_hits: list[tuple[str, int, str]] = []
    for rel_path in tracked_files():
        if rel_path in EXCLUDE_PATHS or any(rel_path.startswith(d) for d in EXCLUDE_DIRS):
            continue
        path = ROOT / rel_path
        suffix = path.suffix
        if suffix not in SOURCE_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if MARKER_PATTERN.search(line):
                markers.append((rel_path, lineno, line.strip()))
            if rel_path.startswith("tests/") and MOCK_PATTERN.search(line):
                mock_hits.append((rel_path, lineno, line.strip()))
    return markers, mock_hits


def render(markers: list[tuple[str, int, str]], mock_hits: list[tuple[str, int, str]]) -> str:
    date = dt.date.today().isoformat()
    tree_sha = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, check=True, text=True
    ).stdout.strip()
    lines = [
        f"# Stub / WIP Audit — {date}",
        "",
        "Status: `" + ("PARTIAL_ALIVE" if markers or mock_hits else "ALIVE") + "`",
        "",
        "## Admitted subject",
        "",
        "- Repository: `seanchatmangpt/chatman-ecosystem`",
        "- Base: `main`",
        f"- Observed tree SHA: `{tree_sha}`",
        "",
        "## Method",
        "",
        "Generated by `scripts/audit_stubs_wip.py`, which scans `git ls-files` for "
        "stub/WIP markers (`TODO`, `FIXME`, `XXX`, `unimplemented!`, `todo!`, `stub!`) "
        "in tracked source/doc files, and for banned mock-double patterns "
        "(`unittest.mock`, `MagicMock`, `jest.mock`, `monkeypatch`) under `tests/` "
        "per AGENTS.md rule 8/9 and the Chicago-style testing discipline.",
        "",
        "## Findings",
        "",
    ]
    if markers:
        lines.append(f"### WIP-STUB-MARKERS — {len(markers)} marker(s) found")
        lines.append("")
        lines.append("**Classification:** `INCOMPLETE_WIP`")
        lines.append("")
        for rel_path, lineno, content in markers:
            lines.append(f"- `{rel_path}:{lineno}` — `{content}`")
        lines.append("")
    else:
        lines.append("### WIP-STUB-MARKERS — none found")
        lines.append("")
        lines.append(
            "No `TODO`/`FIXME`/`XXX`/`unimplemented!`/`todo!`/`stub!` markers were "
            "found in tracked source or doc files."
        )
        lines.append("")
    if mock_hits:
        lines.append(f"### WIP-MOCK-DOUBLES — {len(mock_hits)} banned mock pattern(s) found")
        lines.append("")
        lines.append("**Classification:** `TESTING_DISCIPLINE_VIOLATION`")
        lines.append("")
        for rel_path, lineno, content in mock_hits:
            lines.append(f"- `{rel_path}:{lineno}` — `{content}`")
        lines.append("")
    else:
        lines.append("### WIP-MOCK-DOUBLES — none found")
        lines.append("")
        lines.append(
            "No `unittest.mock`/`MagicMock`/`jest.mock`/`monkeypatch` usage was found "
            "under `tests/`."
        )
        lines.append("")
    lines.append("## Standing")
    lines.append("")
    if markers or mock_hits:
        lines.append(
            "`PARTIAL_ALIVE`: exact default-branch tree was observed and markers were "
            "found; closure requires resolving each listed finding."
        )
    else:
        lines.append(
            "`ALIVE`: exact default-branch tree was observed and no stub/WIP markers "
            "or banned mock-double patterns were found by this scan's method."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write docs/audits/<date>-stubs-wip.md")
    args = parser.parse_args()

    markers, mock_hits = scan()
    content = render(markers, mock_hits)

    if args.write:
        date = dt.date.today().isoformat()
        out_path = ROOT / "docs" / "audits" / f"{date}-stubs-wip.md"
        out_path.write_text(content)
        print(f"wrote {out_path.relative_to(ROOT)}", file=sys.stderr)
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
