#!/bin/sh
# CE23-12-GeneratedQualificationPlan court: CE23-12 conjunct GeneratedQualificationPlan (release/v26.9.23/sjira/goal.ttl ce:CE23-12-GeneratedQualificationPlan).
# Run from the chatman-ecosystem root by the CE23 root court. Exit 0 = ALIVE; exit 75 = machinery,
# a tool or a canonical checkout absent (standing UNKNOWN); exit 1 carries typed REFUSED[<code>] lines
# naming the counterexample; any other exit = the court ran and witnessed nothing (standing UNKNOWN).
# Machinery (step CE23-12, orders CE23-12-BD-03/04/07/08): release/v26.9.23/courts/ce23_12/court.py gqp
# judges the exact committed head: the DOE support matrix is a ggen projection of the factor graph whose
# independently computed resolution equals the declared one with the OS factor UNSUPPORTED (no column,
# not varied, one macOS runner) (A1); the statistical acceptance rules are kernel output with tiers
# 30 < 100 < 300 < 3000 and exact zero-defect bounds, and a zero-failure run is never read past its tier
# (A2); the benchmark work orders are generated by the pack's plan CONSTRUCT, cover every class x
# family, MSA court, capability gap and successor reference order, and conform to the semantic-jira-pack
# work-order shapes (A4 A4s); the prose-derived CE23-12 orders recompute (A4p, compile_check.sh);
# the cross-OS evidence ceiling is stated (O1); then the anti-vacuity corpus.
here=$(cd "$(dirname "$0")" && pwd)
command -v python3 >/dev/null 2>&1 || { echo "UNKNOWN[TOOL_MISSING] CE23-12-GeneratedQualificationPlan: python3 not on PATH"; exit 75; }
[ -f "$here/ce23_12/court.py" ] || { echo "UNKNOWN[MACHINERY_ABSENT] CE23-12-GeneratedQualificationPlan: $here/ce23_12/court.py"; exit 75; }
PYTHONDONTWRITEBYTECODE=1 exec python3 "$here/ce23_12/court.py" gqp "$@"
