from enum import Enum
class Failure(str,Enum): TRACE_DIVERGENCE="TRACE_DIVERGENCE"; ORACLE_COLLUSION="ORACLE_COLLUSION"; STALE="STALE"; SPLIT_GENERATION="SPLIT_GENERATION"; TLS_CONTRADICTION="TLS_CONTRADICTION"; BRCE_MISMATCH="BRCE_MISMATCH"; REPLAY_MISMATCH="REPLAY_MISMATCH"
def standing(failures): return "UNKNOWN" if failures else "PARTIAL_ALIVE"
