"""Pure per-file and per-tree measures for the release scorecard (stdlib only, no I/O).

Every measure is a function of (path, bytes) pairs, so a test can feed it literal trees and
the observer can feed it a streamed ``git archive``; the definitions below are the ones the
scorecard cites.

* text file: at most ``MAX_TEXT_BYTES`` bytes, no NUL in the first 8 KiB, valid UTF-8.
* LOC: non-blank lines of a text file.
* generated file: a text file whose first ``HEADER_BYTES`` bytes match ``GENERATED_MARKERS``
  (``GENERATED by`` | ``Generated by ggen`` | ``@generated`` | ``DO NOT EDIT``).
* handwritten file: a path named by the first column of a ``HANDWRITTEN.md`` ledger row
  (``path | element | missing capability | owner pack | date``) of the same tree; entries are
  split on ``,``/``;``, parenthetical notes dropped, ``{a,b}`` expanded, ``*`` globbed, a
  trailing ``/`` is a directory prefix.
* marketplace-reused file: a text file (outside ggen-marketplace) with at least
  ``MIN_REUSE_LOC`` LOC whose git blob id is a blob of the pinned ggen-marketplace tree.
* duplicated LOC: over new derivable surfaces (non-generated text files with a
  ``DERIVABLE_EXT`` extension whose blob changed since the predecessor pin), lines covered
  by a ``WINDOW``-line window of normalized lines that occurs at two or more locations.
"""

from __future__ import annotations

import fnmatch
import hashlib
import re
from dataclasses import dataclass, field
from typing import Iterable

GENERATED_MARKERS = re.compile(rb"GENERATED by|Generated by ggen|@generated|DO NOT EDIT")
HEADER_BYTES = 4096
MAX_TEXT_BYTES = 2 * 1024 * 1024
MIN_REUSE_LOC = 5
WINDOW = 6
DERIVABLE_EXT = (
    ".py", ".ex", ".exs", ".rs", ".ts", ".tsx", ".js", ".mjs", ".sh", ".yml", ".yaml",
    ".toml", ".ttl", ".rq", ".tera", ".tmpl", ".j2", ".hbs", ".sql", ".go", ".erl",
)
LEDGER_NAME = "HANDWRITTEN.md"
_TRIVIAL = re.compile(r"^[\W_]*$")


def parameters() -> dict[str, object]:
    return {
        "generated_markers": GENERATED_MARKERS.pattern.decode(),
        "header_bytes": HEADER_BYTES,
        "max_text_bytes": MAX_TEXT_BYTES,
        "min_reuse_loc": MIN_REUSE_LOC,
        "window": WINDOW,
        "derivable_ext": list(DERIVABLE_EXT),
        "ledger_name": LEDGER_NAME,
        "loc": "non-blank lines of a UTF-8 text file",
    }


def blob_sha(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def text_of(data: bytes) -> str | None:
    if len(data) > MAX_TEXT_BYTES or b"\0" in data[:8192]:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return None


def loc_of(text: str) -> int:
    return sum(1 for line in text.splitlines() if line.strip())


def is_generated(data: bytes) -> bool:
    return GENERATED_MARKERS.search(data[:HEADER_BYTES]) is not None


def normalize(line: str) -> str | None:
    """Whitespace-collapsed line, or None for blank / punctuation-only lines."""
    text = " ".join(line.split())
    if not text or _TRIVIAL.fullmatch(text):
        return None
    return text


def _expand_braces(token: str) -> list[str]:
    match = re.search(r"\{([^{}]*)\}", token)
    if match is None:
        return [token]
    head, tail = token[: match.start()], token[match.end() :]
    out: list[str] = []
    for option in match.group(1).split(","):
        out.extend(_expand_braces(head + option.strip() + tail))
    return out


def _split_top(text: str) -> list[str]:
    """Split on ``,``/``;``/whitespace outside ``{...}`` (brace groups stay whole)."""
    out, cur, depth = [], [], 0
    for ch in text:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
        if depth == 0 and (ch in ",;" or ch.isspace()):
            out.append("".join(cur))
            cur = []
            continue
        cur.append(ch)
    out.append("".join(cur))
    return out


def ledger_entries(markdown: str) -> list[str]:
    """Path patterns named by the first column of each ``|``-separated ledger row."""
    entries: list[str] = []
    for line in markdown.splitlines():
        if " | " not in line or line.lstrip().startswith(("#", "Format:", "`path")):
            continue
        first = line.split(" | ", 1)[0]
        first = re.sub(r"\([^()]*\)", " ", first)
        for token in _split_top(first):
            token = token.strip().strip("`").rstrip(".:")
            if not token or ("/" not in token and "." not in token):
                continue
            for expanded in _expand_braces(token):
                if expanded not in entries:
                    entries.append(expanded)
    return entries


def match_entries(entries: Iterable[str], paths: Iterable[str], base: str = "") -> tuple[set[str], list[str]]:
    """(matched paths, entries that matched nothing). ``base`` is the ledger's directory."""
    universe = sorted(paths)
    present = set(universe)
    matched: set[str] = set()
    unmatched: list[str] = []
    for entry in entries:
        pattern = f"{base}{entry}" if base and not entry.startswith(base) else entry
        if pattern.endswith("/"):
            hits = [p for p in universe if p.startswith(pattern)]
        elif any(ch in pattern for ch in "*?["):
            hits = [p for p in universe if fnmatch.fnmatchcase(p, pattern)]
        else:
            hits = [pattern] if pattern in present else [p for p in universe if p.startswith(pattern + "/")]
        if hits:
            matched.update(hits)
        else:
            unmatched.append(entry)
    return matched, unmatched


@dataclass
class FileFacts:
    blob: str
    loc: int | None  # None: not a text file
    generated: bool


@dataclass
class TreeMeasure:
    files: dict[str, FileFacts] = field(default_factory=dict)
    ledgers: dict[str, str] = field(default_factory=dict)
    derivable: dict[str, list[str]] = field(default_factory=dict)  # path -> raw lines (kept on demand)

    def add(self, path: str, data: bytes, keep_lines: bool = False) -> None:
        text = text_of(data)
        facts = FileFacts(blob_sha(data), loc_of(text) if text is not None else None, text is not None and is_generated(data))
        self.files[path] = facts
        if text is not None and path.rsplit("/", 1)[-1] == LEDGER_NAME:
            self.ledgers[path] = text
        if keep_lines and text is not None and not facts.generated and path.endswith(DERIVABLE_EXT):
            self.derivable[path] = text.splitlines()

    def summary(self, marketplace_blobs: set[str] | None) -> dict[str, object]:
        text = {p: f for p, f in self.files.items() if f.loc is not None}
        generated = {p: f for p, f in text.items() if f.generated}
        matched: set[str] = set()
        unmatched: list[str] = []
        entries = 0
        for ledger, body in sorted(self.ledgers.items()):
            base = ledger[: -len(LEDGER_NAME)]
            found = ledger_entries(body)
            entries += len(found)
            hit, miss = match_entries(found, self.files, base)
            # root-relative entries in a nested ledger are also tried from the root
            if base:
                hit_root, miss = match_entries(miss, self.files)
                hit |= hit_root
            matched |= hit
            unmatched += [f"{ledger}:{m}" for m in miss]
        handwritten = {p for p in matched if p in text}
        reused: dict[str, FileFacts] = {}
        if marketplace_blobs is not None:
            reused = {
                p: f for p, f in text.items() if (f.loc or 0) >= MIN_REUSE_LOC and f.blob in marketplace_blobs
            }
        return {
            "files": len(self.files),
            "text_files": len(text),
            "loc": sum(f.loc or 0 for f in text.values()),
            "generated_files": len(generated),
            "generated_loc": sum(f.loc or 0 for f in generated.values()),
            "handwritten": {
                "ledgers": sorted(self.ledgers),
                "entries": entries,
                "matched_files": len(handwritten),
                "loc": sum(text[p].loc or 0 for p in handwritten),
                "unmatched_entries": sorted(unmatched),
            },
            "marketplace_reused_files": len(reused) if marketplace_blobs is not None else None,
            "marketplace_reused_loc": sum(f.loc or 0 for f in reused.values()) if marketplace_blobs is not None else None,
        }


def duplicated_lines(surfaces: dict[str, list[str]]) -> dict[str, object]:
    """Lines of ``surfaces`` (location -> raw lines) covered by a repeated normalized window."""
    occurrences: dict[str, list[tuple[str, int]]] = {}
    normalized: dict[str, list[tuple[int, str]]] = {}
    total = 0
    for location in sorted(surfaces):
        kept = [(i, n) for i, n in ((i, normalize(line)) for i, line in enumerate(surfaces[location])) if n is not None]
        normalized[location] = kept
        total += sum(1 for line in surfaces[location] if line.strip())
        for start in range(0, max(0, len(kept) - WINDOW + 1)):
            key = hashlib.sha256("\n".join(n for _, n in kept[start : start + WINDOW]).encode()).hexdigest()
            occurrences.setdefault(key, []).append((location, start))
    covered: set[tuple[str, int]] = set()
    clusters = []
    for key, where in occurrences.items():
        if len(where) < 2:
            continue
        for location, start in where:
            for i, _ in normalized[location][start : start + WINDOW]:
                covered.add((location, i))
        clusters.append((len(where), key, sorted({loc for loc, _ in where})))
    clusters.sort(key=lambda c: (-c[0], c[1]))
    return {
        "new_surface_files": len(surfaces),
        "new_surface_loc": total,
        "duplicated_loc": len(covered),
        "repeated_windows": len(clusters),
        "top_clusters": [
            {"occurrences": n, "window_sha256": key, "locations": locs[:6]} for n, key, locs in clusters[:10]
        ],
    }
